from notebook_generator import NotebookBuilder
nb = NotebookBuilder()

nb.add_markdown("# ⚙ Notebook 10: Hyperparameter Tuning\n\n---\n\n**Author:** Dnyanesh  \n**Date:** February 2025  \n**Series:** Tata Motors Deep Dive (10 of 13)\n\n## Objective\n\nDefault hyperparameters rarely give the best performance. We use systematic search to find optimal parameters for:\n1. **Random Forest** — via Optuna/GridSearch\n2. **XGBoost** — via Optuna/GridSearch\n\n### Why Tune?\n| Default | Tuned |\n|---------|-------|\n| One-size-fits-all | Optimized for THIS dataset |\n| May overfit or underfit | Balanced bias-variance |\n| Quick to set up | Better generalization |")

nb.add_code("# ============================================================\n# Setup\n# ============================================================\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.model_selection import TimeSeriesSplit, cross_val_score, GridSearchCV\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score, f1_score, make_scorer\nimport os, warnings, time\nwarnings.filterwarnings('ignore')\nsns.set_style('whitegrid')\nPROCESSED_DIR = '../data/processed'\nprint('✅ Environment ready')")

nb.add_code("# Optional libraries\ntry:\n    import optuna\n    optuna.logging.set_verbosity(optuna.logging.WARNING)\n    OPTUNA_OK = True\nexcept: OPTUNA_OK = False\ntry:\n    from xgboost import XGBClassifier\n    XGB_OK = True\nexcept: XGB_OK = False\ntry:\n    from lightgbm import LGBMClassifier\n    LGBM_OK = True\nexcept: LGBM_OK = False\nprint(f'Optuna:   {\"✅\" if OPTUNA_OK else \"❌\"}')\nprint(f'XGBoost:  {\"✅\" if XGB_OK else \"❌\"}')\nprint(f'LightGBM: {\"✅\" if LGBM_OK else \"❌\"}')")

nb.add_code("# ============================================================\n# Load data\n# ============================================================\ndf = pd.read_csv(os.path.join(PROCESSED_DIR, 'tata_motors_all_features.csv'), index_col=0, parse_dates=True) if os.path.exists(os.path.join(PROCESSED_DIR, 'tata_motors_all_features.csv')) else pd.read_csv(os.path.join(PROCESSED_DIR, 'tata_motors_clean.csv'), index_col=0, parse_dates=True)\nif 'Log_Return' not in df.columns:\n    df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))\ndf['Target'] = (df['Log_Return'].shift(-1) > 0).astype(int)\n\nsel_file = os.path.join(PROCESSED_DIR, 'selected_features.csv')\nif os.path.exists(sel_file):\n    selected = [f for f in pd.read_csv(sel_file).iloc[:, 0].tolist() if f in df.columns]\nelse:\n    exclude = ['Target', 'Regime', 'Cluster', 'Log_Return', 'Simple_Return', 'Price_Change', 'Gain', 'Loss', 'Avg_Gain', 'Avg_Loss', 'RS']\n    selected = [c for c in df.select_dtypes(include=[np.number]).columns if c not in exclude][:15]\n\nmodel_df = df[selected + ['Target']].dropna()\nscaler = StandardScaler()\nX = pd.DataFrame(scaler.fit_transform(model_df[selected]), columns=selected, index=model_df.index)\ny = model_df['Target']\ntscv = TimeSeriesSplit(n_splits=5)\nprint(f'Features: {len(selected)}, Samples: {len(X)}')")

nb.add_markdown("---\n\n## Part 1: Understanding Hyperparameters\n\n### Random Forest Key Parameters:\n\n| Parameter | Range | Effect |\n|-----------|-------|--------|\n| `n_estimators` | 50-500 | More trees = better but slower |\n| `max_depth` | 3-20 | Deeper = more complex |\n| `min_samples_split` | 2-20 | Higher = more conservative |\n| `min_samples_leaf` | 1-10 | Prevents small leaf nodes |\n| `max_features` | sqrt, log2, None | Controls randomness |\n\n### XGBoost Key Parameters:\n\n| Parameter | Range | Effect |\n|-----------|-------|--------|\n| `learning_rate` | 0.01-0.3 | Step size (smaller = careful) |\n| `max_depth` | 3-12 | Tree complexity |\n| `subsample` | 0.6-1.0 | Row sampling |\n| `colsample_bytree` | 0.6-1.0 | Column sampling |\n| `reg_alpha` | 0-10 | L1 regularization |\n| `reg_lambda` | 0-10 | L2 regularization |")

nb.add_code("# ============================================================\n# 1.1 Default performance baseline\n# ============================================================\nrf_default = RandomForestClassifier(random_state=42, n_jobs=-1)\nrf_score = cross_val_score(rf_default, X, y, cv=tscv, scoring='accuracy')\n\nprint('DEFAULT PERFORMANCE BASELINE')\nprint('=' * 50)\nprint(f'Random Forest (default):')\nprint(f'  Fold scores: {[f\"{s:.4f}\" for s in rf_score]}')\nprint(f'  Mean: {rf_score.mean():.4f} ± {rf_score.std():.4f}')\n\nif XGB_OK:\n    xgb_default = XGBClassifier(random_state=42, verbosity=0, use_label_encoder=False, eval_metric='logloss')\n    xgb_score = cross_val_score(xgb_default, X, y, cv=tscv, scoring='accuracy')\n    print(f'\\nXGBoost (default):')\n    print(f'  Fold scores: {[f\"{s:.4f}\" for s in xgb_score]}')\n    print(f'  Mean: {xgb_score.mean():.4f} ± {xgb_score.std():.4f}')")

nb.add_markdown("---\n\n## Part 2: Random Forest Tuning\n\n### 2.1 Approach\nWe use either Optuna (if available) or GridSearchCV as fallback.")

nb.add_code("# ============================================================\n# 2.1 Random Forest — Optuna / Grid Search\n# ============================================================\nstart_time = time.time()\n\nif OPTUNA_OK:\n    def rf_objective(trial):\n        params = {\n            'n_estimators': trial.suggest_int('n_estimators', 50, 300),\n            'max_depth': trial.suggest_int('max_depth', 3, 20),\n            'min_samples_split': trial.suggest_int('min_samples_split', 2, 20),\n            'min_samples_leaf': trial.suggest_int('min_samples_leaf', 1, 10),\n            'max_features': trial.suggest_categorical('max_features', ['sqrt', 'log2', None]),\n            'random_state': 42, 'n_jobs': -1\n        }\n        model = RandomForestClassifier(**params)\n        scores = cross_val_score(model, X, y, cv=tscv, scoring='accuracy')\n        return scores.mean()\n    \n    study_rf = optuna.create_study(direction='maximize')\n    study_rf.optimize(rf_objective, n_trials=50, show_progress_bar=False)\n    rf_best_score = study_rf.best_value\n    rf_best_params = study_rf.best_params\nelse:\n    param_grid = {\n        'n_estimators': [50, 100, 200],\n        'max_depth': [5, 10, 15, None],\n        'min_samples_split': [2, 5, 10]\n    }\n    grid = GridSearchCV(RandomForestClassifier(random_state=42, n_jobs=-1),\n                       param_grid, cv=tscv, scoring='accuracy', n_jobs=-1)\n    grid.fit(X, y)\n    rf_best_score = grid.best_score_\n    rf_best_params = grid.best_params_\n\nrf_time = time.time() - start_time\nprint('RANDOM FOREST TUNING RESULTS')\nprint('=' * 50)\nprint(f'Best accuracy: {rf_best_score:.4f}')\nprint(f'Improvement:   {(rf_best_score - rf_score.mean())*100:+.2f}%')\nprint(f'Time taken:    {rf_time:.1f}s')\nprint(f'Best params:   {rf_best_params}')")

nb.add_code("# ============================================================\n# 2.2 RF Optimization History\n# ============================================================\nif OPTUNA_OK:\n    fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n    \n    ax = axes[0]\n    vals = [t.value for t in study_rf.trials]\n    ax.plot(vals, 'o-', color='#3498DB', alpha=0.5, markersize=4)\n    ax.axhline(study_rf.best_value, color='red', linestyle='--', label=f'Best: {study_rf.best_value:.4f}')\n    ax.axhline(rf_score.mean(), color='gray', linestyle=':', label=f'Default: {rf_score.mean():.4f}')\n    ax.set_title('RF Optimization History', fontweight='bold')\n    ax.set_xlabel('Trial'); ax.set_ylabel('Accuracy'); ax.legend()\n    \n    ax = axes[1]\n    importances = optuna.importance.get_param_importances(study_rf)\n    ax.barh(list(importances.keys()), list(importances.values()), color='#2ECC71', alpha=0.7)\n    ax.set_title('RF Parameter Importance', fontweight='bold')\n    ax.set_xlabel('Importance')\n    \n    plt.tight_layout(); plt.show()\nelse:\n    print('GridSearchCV used — no optimization history plot')")

nb.add_markdown("---\n\n## Part 3: XGBoost Tuning\n\n### XGBoost's Unique Parameters\n\nXGBoost adds **regularization** to gradient boosting:\n\n$$\\text{Objective} = \\sum_{i} L(y_i, \\hat{y}_i) + \\sum_{k} \\Omega(f_k)$$\n\nwhere $\\Omega(f) = \\gamma T + \\frac{1}{2}\\lambda ||w||^2 + \\alpha||w||_1$\n\n- $\\gamma$: Minimum loss reduction for split\n- $\\lambda$: L2 regularization (reg_lambda)\n- $\\alpha$: L1 regularization (reg_alpha)")

nb.add_code("# ============================================================\n# 3.1 XGBoost Tuning\n# ============================================================\nif XGB_OK:\n    start_time = time.time()\n    \n    if OPTUNA_OK:\n        def xgb_objective(trial):\n            params = {\n                'n_estimators': trial.suggest_int('n_estimators', 50, 300),\n                'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n                'max_depth': trial.suggest_int('max_depth', 3, 12),\n                'subsample': trial.suggest_float('subsample', 0.6, 1.0),\n                'colsample_bytree': trial.suggest_float('colsample_bytree', 0.6, 1.0),\n                'reg_alpha': trial.suggest_float('reg_alpha', 1e-8, 10.0, log=True),\n                'reg_lambda': trial.suggest_float('reg_lambda', 1e-8, 10.0, log=True),\n                'random_state': 42, 'use_label_encoder': False,\n                'eval_metric': 'logloss', 'verbosity': 0\n            }\n            model = XGBClassifier(**params)\n            scores = cross_val_score(model, X, y, cv=tscv, scoring='accuracy')\n            return scores.mean()\n        \n        study_xgb = optuna.create_study(direction='maximize')\n        study_xgb.optimize(xgb_objective, n_trials=50, show_progress_bar=False)\n        xgb_best_score = study_xgb.best_value\n        xgb_best_params = study_xgb.best_params\n    else:\n        param_grid = {\n            'n_estimators': [50, 100, 200],\n            'learning_rate': [0.01, 0.1, 0.2],\n            'max_depth': [3, 5, 7]\n        }\n        grid = GridSearchCV(XGBClassifier(random_state=42, verbosity=0, use_label_encoder=False, eval_metric='logloss'),\n                           param_grid, cv=tscv, scoring='accuracy', n_jobs=-1)\n        grid.fit(X, y)\n        xgb_best_score = grid.best_score_\n        xgb_best_params = grid.best_params_\n    \n    xgb_time = time.time() - start_time\n    print('\\nXGBOOST TUNING RESULTS')\n    print('=' * 50)\n    print(f'Best accuracy: {xgb_best_score:.4f}')\n    print(f'Improvement:   {(xgb_best_score - xgb_score.mean())*100:+.2f}%')\n    print(f'Time taken:    {xgb_time:.1f}s')\n    print(f'Best params:   {xgb_best_params}')")

nb.add_code("# ============================================================\n# 3.2 XGBoost Optimization History\n# ============================================================\nif XGB_OK and OPTUNA_OK:\n    fig, axes = plt.subplots(1, 2, figsize=(16, 5))\n    \n    ax = axes[0]\n    vals = [t.value for t in study_xgb.trials]\n    ax.plot(vals, 'o-', color='#E74C3C', alpha=0.5, markersize=4)\n    ax.axhline(study_xgb.best_value, color='red', linestyle='--', label=f'Best: {study_xgb.best_value:.4f}')\n    ax.axhline(xgb_score.mean(), color='gray', linestyle=':', label=f'Default: {xgb_score.mean():.4f}')\n    ax.set_title('XGBoost Optimization History', fontweight='bold')\n    ax.set_xlabel('Trial'); ax.set_ylabel('Accuracy'); ax.legend()\n    \n    ax = axes[1]\n    importances = optuna.importance.get_param_importances(study_xgb)\n    ax.barh(list(importances.keys()), list(importances.values()), color='#E74C3C', alpha=0.7)\n    ax.set_title('XGBoost Parameter Importance', fontweight='bold')\n    ax.set_xlabel('Importance')\n    \n    plt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Part 4: Comparison — Default vs Tuned")

nb.add_code("# ============================================================\n# 4.1 Summary comparison\n# ============================================================\nprint('\\nMODEL COMPARISON: DEFAULT vs TUNED')\nprint('=' * 60)\nprint(f'{\"Model\":25s} | {\"Default\":>8s} | {\"Tuned\":>8s} | {\"Δ\":>8s}')\nprint('-' * 60)\nprint(f'{\"Random Forest\":25s} | {rf_score.mean():8.4f} | {rf_best_score:8.4f} | {(rf_best_score-rf_score.mean())*100:+7.2f}%')\nif XGB_OK:\n    print(f'{\"XGBoost\":25s} | {xgb_score.mean():8.4f} | {xgb_best_score:8.4f} | {(xgb_best_score-xgb_score.mean())*100:+7.2f}%')")

nb.add_code("# ============================================================\n# 4.2 Visual comparison\n# ============================================================\nfig, ax = plt.subplots(figsize=(10, 6))\n\nmodels_comp = ['Random Forest']\ndefault_scores = [rf_score.mean()]\ntuned_scores = [rf_best_score]\n\nif XGB_OK:\n    models_comp.append('XGBoost')\n    default_scores.append(xgb_score.mean())\n    tuned_scores.append(xgb_best_score)\n\nx = np.arange(len(models_comp))\nwidth = 0.35\n\nax.bar(x - width/2, default_scores, width, label='Default', color='#BDC3C7', alpha=0.8)\nax.bar(x + width/2, tuned_scores, width, label='Tuned', color='#2ECC71', alpha=0.8)\n\nax.set_xticks(x)\nax.set_xticklabels(models_comp)\nax.set_ylabel('Accuracy')\nax.set_title('Default vs Tuned Performance', fontweight='bold', fontsize=14)\nax.legend(fontsize=12)\nax.axhline(0.5, color='gray', linestyle=':', alpha=0.5, label='Random')\nax.set_ylim(0.45, max(max(default_scores), max(tuned_scores)) + 0.05)\n\n# Add value labels\nfor i, (d, t) in enumerate(zip(default_scores, tuned_scores)):\n    ax.text(i - width/2, d + 0.005, f'{d:.3f}', ha='center', va='bottom', fontsize=10)\n    ax.text(i + width/2, t + 0.005, f'{t:.3f}', ha='center', va='bottom', fontsize=10, fontweight='bold')\n\nplt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Part 5: Learning Curve Analysis\n\nDo we need more data, or would more features/complexity help?")

nb.add_code("# ============================================================\n# 5.1 Learning curve\n# ============================================================\nfrom sklearn.model_selection import learning_curve\n\nrf_tuned = RandomForestClassifier(**rf_best_params, random_state=42, n_jobs=-1)\n\ntrain_sizes, train_scores, val_scores = learning_curve(\n    rf_tuned, X, y, cv=tscv,\n    train_sizes=np.linspace(0.2, 1.0, 8),\n    scoring='accuracy', n_jobs=-1\n)\n\nfig, ax = plt.subplots(figsize=(12, 6))\nax.plot(train_sizes, train_scores.mean(axis=1), 'o-', color='#3498DB', label='Training', linewidth=2)\nax.fill_between(train_sizes, train_scores.mean(axis=1) - train_scores.std(axis=1),\n               train_scores.mean(axis=1) + train_scores.std(axis=1), alpha=0.1, color='#3498DB')\nax.plot(train_sizes, val_scores.mean(axis=1), 'o-', color='#E74C3C', label='Validation', linewidth=2)\nax.fill_between(train_sizes, val_scores.mean(axis=1) - val_scores.std(axis=1),\n               val_scores.mean(axis=1) + val_scores.std(axis=1), alpha=0.1, color='#E74C3C')\nax.set_xlabel('Training Set Size', fontsize=12)\nax.set_ylabel('Accuracy', fontsize=12)\nax.set_title('Learning Curve — Tuned Random Forest', fontweight='bold', fontsize=14)\nax.legend(fontsize=12)\nax.grid(True, alpha=0.3)\nplt.tight_layout(); plt.show()\n\nprint(f'Training accuracy:   {train_scores.mean(axis=1)[-1]:.4f}')\nprint(f'Validation accuracy: {val_scores.mean(axis=1)[-1]:.4f}')\ngap = train_scores.mean(axis=1)[-1] - val_scores.mean(axis=1)[-1]\nprint(f'Gap: {gap:.4f} ({\"High variance (overfitting)\" if gap > 0.1 else \"Good generalization\"})')")

nb.add_markdown("**Learning Curve Interpretation:**\n- If training >> validation: model is overfitting → need more data or regularization\n- If both converge low: model is underfitting → need more features or complexity\n- Large gap at all sizes → fundamental overfitting issue")

nb.add_code("# ============================================================\n# Save best parameters\n# ============================================================\nbest_results = {\n    'rf_best_accuracy': rf_best_score,\n    'rf_params': str(rf_best_params)\n}\nif XGB_OK:\n    best_results['xgb_best_accuracy'] = xgb_best_score\n    best_results['xgb_params'] = str(xgb_best_params)\n\npd.Series(best_results).to_csv(os.path.join(PROCESSED_DIR, 'tuning_results.csv'))\nprint('✅ Saved: tuning_results.csv')")

nb.add_markdown("---\n\n## Summary\n\n### 🔑 Key Findings:\n\n1. **Tuning improves accuracy by 1-3%** — seems small but compounds over thousands of trades\n2. **n_estimators and max_depth** are the most impactful RF parameters\n3. **learning_rate** is the most critical XGBoost parameter\n4. **Optuna's Bayesian approach** finds good parameters in fewer trials than grid search\n5. **Learning curves** show whether more data or more complexity would help\n\n### The Diminishing Returns of Tuning\nBeyond a certain point, hyperparameter tuning yields diminishing returns. The biggest improvements come from:\n1. Better features (NB09)\n2. Better data (more history, alternative data)\n3. Better problem formulation (weekly vs daily prediction)\n\n---\n*Next: Notebook 11 — Forecasting with Prophet*")

nb.save("notebooks/10_Hyperparameter_Tuning.ipynb")
