from notebook_generator import NotebookBuilder
nb = NotebookBuilder()

nb.add_markdown("# 🤖 Notebook 08: Model Baseline Comparison\n\n---\n\n**Author:** Dnyanesh  \n**Date:** February 2025  \n**Series:** Tata Motors Deep Dive (8 of 13)\n\n## Objective\n\nCompare multiple ML models for predicting Tata Motors' next-day return direction:\n1. **Logistic Regression** — Linear baseline\n2. **Random Forest** — Ensemble of decision trees\n3. **XGBoost** — Gradient boosting (state-of-the-art)\n4. **LightGBM** — Fast gradient boosting\n\nUsing **TimeSeriesSplit** cross-validation to prevent data leakage.\n\n### Why Direction, Not Price?\n\n$$P(\\text{tomorrow\\_up}) = f(\\text{features\\_today})$$\n\nPredicting exact price is nearly impossible. Predicting *direction* (up/down) is:\n- More achievable (binary classification)\n- Directly actionable for trading\n- Measurable with standard ML metrics")

nb.add_code("# ============================================================\n# Setup\n# ============================================================\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.model_selection import TimeSeriesSplit\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import (accuracy_score, precision_score, recall_score,\n                             f1_score, classification_report, confusion_matrix,\n                             roc_auc_score, roc_curve)\nimport os, warnings\nwarnings.filterwarnings('ignore')\nsns.set_style('whitegrid')\nPROCESSED_DIR = '../data/processed'\nprint('✅ Environment ready')")

nb.add_code("# ============================================================\n# Check optional boosting libraries\n# ============================================================\ntry:\n    from xgboost import XGBClassifier\n    XGB_OK = True\nexcept: XGB_OK = False\ntry:\n    from lightgbm import LGBMClassifier\n    LGBM_OK = True\nexcept: LGBM_OK = False\nprint(f'XGBoost:  {\"✅\" if XGB_OK else \"❌ Not available\"}')\nprint(f'LightGBM: {\"✅\" if LGBM_OK else \"❌ Not available\"}')")

nb.add_markdown("---\n\n## Part 1: Data Preparation\n\n### 1.1 Target Variable\n\nWe create a binary target:\n- **1 (UP)**: Next-day log return > 0\n- **0 (DOWN)**: Next-day log return ≤ 0\n\n> **Critical:** We use `shift(-1)` for the target to predict TOMORROW's direction using TODAY's features. This prevents **look-ahead bias** — the most common mistake in financial ML.")

nb.add_code("# ============================================================\n# 1.1 Load and prepare data\n# ============================================================\nfilepath = os.path.join(PROCESSED_DIR, 'tata_motors_all_features.csv')\nif os.path.exists(filepath):\n    df = pd.read_csv(filepath, index_col=0, parse_dates=True)\nelse:\n    df = pd.read_csv(os.path.join(PROCESSED_DIR, 'tata_motors_clean.csv'), index_col=0, parse_dates=True)\n\nprint(f'Loaded: {df.shape}')\nprint(f'Columns: {df.columns.tolist()[:10]}...')")

nb.add_code("# ============================================================\n# 1.2 Create target variable\n# ============================================================\nif 'Log_Return' not in df.columns:\n    df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))\n\ndf['Target'] = (df['Log_Return'].shift(-1) > 0).astype(int)\n\nprint('Target Variable Distribution:')\nprint(df['Target'].value_counts())\nprint(f'\\nUp days:   {df[\"Target\"].mean()*100:.1f}%')\nprint(f'Down days: {(1-df[\"Target\"].mean())*100:.1f}%')\nprint(f'\\nBaseline accuracy (always predict majority): {max(df[\"Target\"].mean(), 1-df[\"Target\"].mean())*100:.1f}%')")

nb.add_markdown("**Important:** The class balance is close to 50/50. A model that always predicts 'UP' would get ~50% accuracy. We need to **beat this baseline** to add value.")

nb.add_code("# ============================================================\n# 1.3 Feature selection\n# ============================================================\nexclude = ['Target', 'Regime', 'Cluster', 'Log_Return', 'Simple_Return',\n           'Price_Change', 'Gain', 'Loss', 'Avg_Gain', 'Avg_Loss', 'RS']\nfeature_cols = [c for c in df.select_dtypes(include=[np.number]).columns if c not in exclude]\n\n# Remove features with too many NaNs\nna_pct = df[feature_cols].isna().mean()\nvalid_features = na_pct[na_pct < 0.3].index.tolist()\n\nprint(f'Total numeric features:  {len(feature_cols)}')\nprint(f'Valid features (< 30% NaN): {len(valid_features)}')\nprint(f'\\nFeatures included:')\nfor i, f in enumerate(valid_features):\n    print(f'  {i+1:2d}. {f}')")

nb.add_code("# ============================================================\n# 1.4 Clean dataset\n# ============================================================\nmodel_df = df[valid_features + ['Target']].dropna()\nX = model_df[valid_features]\ny = model_df['Target']\n\nprint(f'Clean dataset: {X.shape[0]} rows × {X.shape[1]} features')\nprint(f'Target balance: {y.mean():.3f} (UP) / {1-y.mean():.3f} (DOWN)')\nprint(f'Date range: {model_df.index.min().date()} to {model_df.index.max().date()}')")

nb.add_markdown("---\n\n## Part 2: Time Series Cross-Validation\n\n### Why NOT Random K-Fold?\n\nWith time series data, random splitting causes **data leakage**:\n- Model trains on future data and predicts past → unrealistically high accuracy\n- In reality, we can only train on past data\n\n**TimeSeriesSplit** ensures chronological ordering:\n```\nFold 1: [===Train===][Test]\nFold 2: [=====Train=====][Test]\nFold 3: [=======Train=======][Test]\nFold 4: [=========Train=========][Test]\nFold 5: [===========Train===========][Test]\n```")

nb.add_code("# ============================================================\n# 2.1 Scale features\n# ============================================================\nscaler = StandardScaler()\nX_scaled = pd.DataFrame(\n    scaler.fit_transform(X),\n    columns=X.columns, index=X.index\n)\n\nprint('Feature scaling applied (StandardScaler)')\nprint(f'  Mean of first feature: {X_scaled.iloc[:,0].mean():.6f} (should be ~0)')\nprint(f'  Std of first feature:  {X_scaled.iloc[:,0].std():.6f} (should be ~1)')")

nb.add_code("# ============================================================\n# 2.2 Define models\n# ============================================================\nmodels = {\n    'Logistic Regression': LogisticRegression(max_iter=1000, random_state=42),\n    'Random Forest': RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)\n}\nif XGB_OK:\n    models['XGBoost'] = XGBClassifier(\n        n_estimators=100, learning_rate=0.1, random_state=42,\n        use_label_encoder=False, eval_metric='logloss', verbosity=0\n    )\nif LGBM_OK:\n    models['LightGBM'] = LGBMClassifier(\n        n_estimators=100, learning_rate=0.1, random_state=42, verbose=-1\n    )\n\nprint(f'Models to evaluate ({len(models)}):')\nfor name in models:\n    print(f'  • {name}')")

nb.add_markdown("---\n\n## Part 3: Model Training & Evaluation\n\n### Metrics We Track:\n\n| Metric | What It Measures | Why It Matters |\n|--------|-----------------|----------------|\n| **Accuracy** | Overall correctness | Basic performance |\n| **Precision** | Of predicted UPs, how many were correct? | Reduces false buys |\n| **Recall** | Of actual UPs, how many did we catch? | Don't miss opportunities |\n| **F1** | Harmonic mean of precision & recall | Balanced metric |\n| **AUC** | Discrimination ability | Model ranking |")

nb.add_code("# ============================================================\n# 3.1 Cross-validation loop\n# ============================================================\ntscv = TimeSeriesSplit(n_splits=5)\n\nall_results = {}\nfold_details = {}\n\nfor name, model in models.items():\n    fold_metrics = []\n    \n    for fold, (train_idx, test_idx) in enumerate(tscv.split(X_scaled)):\n        X_train = X_scaled.iloc[train_idx]\n        X_test = X_scaled.iloc[test_idx]\n        y_train = y.iloc[train_idx]\n        y_test = y.iloc[test_idx]\n        \n        model.fit(X_train, y_train)\n        y_pred = model.predict(X_test)\n        y_prob = model.predict_proba(X_test)[:, 1] if hasattr(model, 'predict_proba') else y_pred.astype(float)\n        \n        fold_metrics.append({\n            'Fold': fold + 1,\n            'Train_Size': len(train_idx),\n            'Test_Size': len(test_idx),\n            'Accuracy': accuracy_score(y_test, y_pred),\n            'Precision': precision_score(y_test, y_pred, zero_division=0),\n            'Recall': recall_score(y_test, y_pred, zero_division=0),\n            'F1': f1_score(y_test, y_pred, zero_division=0),\n            'AUC': roc_auc_score(y_test, y_prob) if len(np.unique(y_test)) > 1 else 0.5\n        })\n    \n    fold_df = pd.DataFrame(fold_metrics)\n    fold_details[name] = fold_df\n    all_results[name] = fold_df[['Accuracy', 'Precision', 'Recall', 'F1', 'AUC']].mean()\n    \n    print(f'\\n{name}:')\n    print(f'  Avg Acc: {all_results[name][\"Accuracy\"]:.3f} | F1: {all_results[name][\"F1\"]:.3f} | AUC: {all_results[name][\"AUC\"]:.3f}')")

nb.add_code("# ============================================================\n# 3.2 Results table\n# ============================================================\nresults_df = pd.DataFrame(all_results).T\nresults_df = results_df.round(4)\n\nprint('\\n' + '='*60)\nprint('MODEL PERFORMANCE SUMMARY (5-Fold TimeSeriesSplit)')\nprint('='*60)\nprint(results_df)\n\nbest_model = results_df['Accuracy'].idxmax()\nprint(f'\\n🏆 Best model: {best_model} (Accuracy: {results_df.loc[best_model, \"Accuracy\"]:.4f})')")

nb.add_code("# ============================================================\n# 3.3 Fold-by-fold performance\n# ============================================================\nfor name, fold_df in fold_details.items():\n    print(f'\\n{name} — Per-Fold Results:')\n    print(fold_df.to_string(index=False))")

nb.add_markdown("**Interpretation:** Fold-by-fold results show how stable each model's performance is across time. Large variation between folds = unreliable model. Consistent performance = robust model.")

nb.add_markdown("---\n\n## Part 4: Performance Visualization")

nb.add_code("# ============================================================\n# 4.1 Bar chart comparison\n# ============================================================\nfig, axes = plt.subplots(1, 2, figsize=(18, 6))\n\n# Grouped bar chart\nax = axes[0]\nmetrics_to_plot = ['Accuracy', 'F1', 'AUC']\nx = np.arange(len(results_df))\nwidth = 0.25\ncolors_bar = ['#3498DB', '#2ECC71', '#E74C3C']\n\nfor i, metric in enumerate(metrics_to_plot):\n    ax.bar(x + i*width, results_df[metric], width, label=metric,\n           color=colors_bar[i], alpha=0.8, edgecolor='white')\n\nax.set_xticks(x + width)\nax.set_xticklabels(results_df.index, rotation=30, ha='right')\nax.set_title('Model Performance Comparison', fontweight='bold', fontsize=13)\nax.legend(fontsize=11)\nax.set_ylim(0.3, 0.75)\nax.axhline(0.5, color='gray', linestyle=':', alpha=0.5, label='Random baseline')\n\n# Heatmap\nax = axes[1]\nsns.heatmap(results_df, annot=True, fmt='.3f', cmap='YlOrRd',\n           ax=ax, linewidths=1, linecolor='white')\nax.set_title('Performance Heatmap', fontweight='bold', fontsize=13)\n\nplt.tight_layout(); plt.show()")

nb.add_code("# ============================================================\n# 4.2 ROC Curves\n# ============================================================\nfig, ax = plt.subplots(figsize=(10, 8))\ncolors_roc = ['#3498DB', '#2ECC71', '#E74C3C', '#F39C12']\n\nfor i, (name, model) in enumerate(models.items()):\n    # Use last fold for ROC\n    train_idx, test_idx = list(tscv.split(X_scaled))[-1]\n    model.fit(X_scaled.iloc[train_idx], y.iloc[train_idx])\n    y_prob = model.predict_proba(X_scaled.iloc[test_idx])[:, 1]\n    fpr, tpr, _ = roc_curve(y.iloc[test_idx], y_prob)\n    auc = roc_auc_score(y.iloc[test_idx], y_prob)\n    ax.plot(fpr, tpr, color=colors_roc[i % len(colors_roc)], linewidth=2,\n           label=f'{name} (AUC={auc:.3f})')\n\nax.plot([0, 1], [0, 1], 'k--', alpha=0.5, label='Random')\nax.set_xlabel('False Positive Rate', fontsize=12)\nax.set_ylabel('True Positive Rate', fontsize=12)\nax.set_title('ROC Curves — Model Comparison', fontweight='bold', fontsize=14)\nax.legend(fontsize=11)\nax.grid(True, alpha=0.3)\nplt.tight_layout(); plt.show()")

nb.add_markdown("**ROC Interpretation:**\n- A curve closer to the top-left corner = better discrimination\n- AUC = 0.5 means the model is no better than random guessing\n- AUC > 0.55 for daily stock prediction is considered reasonable\n- The market is efficient — even a small edge is valuable")

nb.add_markdown("---\n\n## Part 5: Feature Importance\n\nWhich features drive the model's predictions?")

nb.add_code("# ============================================================\n# 5.1 Feature importance from tree models\n# ============================================================\nbest_tree = None\nfor name in ['XGBoost', 'LightGBM', 'Random Forest']:\n    if name in models:\n        best_tree = (name, models[name])\n        break\n\nif best_tree:\n    name, model = best_tree\n    model.fit(X_scaled, y)\n    importance = pd.Series(model.feature_importances_, index=valid_features).sort_values(ascending=True)\n    \n    top_n = min(20, len(importance))\n    fig, ax = plt.subplots(figsize=(10, max(8, top_n*0.4)))\n    importance.tail(top_n).plot(kind='barh', ax=ax, color='#3498DB', alpha=0.8, edgecolor='white')\n    ax.set_title(f'Top {top_n} Feature Importances ({name})', fontweight='bold', fontsize=13)\n    ax.set_xlabel('Importance')\n    plt.tight_layout(); plt.show()")

nb.add_code("# ============================================================\n# 5.2 Feature importance table\n# ============================================================\nif best_tree:\n    print(f'\\nFeature Importance Ranking ({best_tree[0]}):')\n    print('=' * 50)\n    for rank, (feat, imp) in enumerate(importance.sort_values(ascending=False).items()):\n        bar = '█' * int(imp / importance.max() * 20)\n        print(f'  {rank+1:2d}. {feat:30s} {imp:.4f} {bar}')")

nb.add_markdown("**Feature Importance Insight:** Volume-related and volatility features tend to rank highest. Price momentum (returns over different windows) is also important. This aligns with financial theory — volume confirms price moves, and volatility predicts regime changes.")

nb.add_markdown("---\n\n## Part 6: Confusion Matrix Analysis")

nb.add_code("# ============================================================\n# 6.1 Confusion matrices for all models\n# ============================================================\ntrain_idx, test_idx = list(tscv.split(X_scaled))[-1]\nX_test_final = X_scaled.iloc[test_idx]\ny_test_final = y.iloc[test_idx]\n\nn_models = len(models)\nfig, axes = plt.subplots(1, n_models, figsize=(5*n_models, 4))\nif n_models == 1: axes = [axes]\n\nfor i, (name, model) in enumerate(models.items()):\n    model.fit(X_scaled.iloc[train_idx], y.iloc[train_idx])\n    y_pred = model.predict(X_test_final)\n    \n    cm = confusion_matrix(y_test_final, y_pred)\n    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[i],\n               xticklabels=['Down', 'Up'], yticklabels=['Down', 'Up'])\n    axes[i].set_xlabel('Predicted')\n    axes[i].set_ylabel('Actual')\n    acc = accuracy_score(y_test_final, y_pred)\n    axes[i].set_title(f'{name}\\n(Acc: {acc:.3f})', fontweight='bold')\n\nplt.tight_layout(); plt.show()")

nb.add_code("# ============================================================\n# 6.2 Classification reports\n# ============================================================\nfor name, model in models.items():\n    model.fit(X_scaled.iloc[train_idx], y.iloc[train_idx])\n    y_pred = model.predict(X_test_final)\n    print(f'\\n{name} Classification Report:')\n    print(classification_report(y_test_final, y_pred, target_names=['Down', 'Up']))")

nb.add_markdown("---\n\n## Part 7: Logistic Regression Coefficients\n\nLogistic Regression is the only model that provides directly interpretable coefficients:\n\n$$P(\\text{UP}) = \\frac{1}{1 + e^{-(\\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\ldots)}}$$\n\nPositive coefficient → feature increases probability of UP.\nNegative coefficient → feature increases probability of DOWN.")

nb.add_code("# ============================================================\n# 7.1 Logistic Regression coefficients\n# ============================================================\nlr = models['Logistic Regression']\nlr.fit(X_scaled, y)\ncoeffs = pd.Series(lr.coef_[0], index=valid_features).sort_values()\n\nfig, ax = plt.subplots(figsize=(10, max(8, len(coeffs)*0.3)))\ntop_n = min(20, len(coeffs))\nbottom = coeffs.head(top_n // 2)\ntop = coeffs.tail(top_n // 2)\nshow = pd.concat([bottom, top])\ncolors_c = ['#E74C3C' if c < 0 else '#2ECC71' for c in show.values]\nshow.plot(kind='barh', ax=ax, color=colors_c, alpha=0.8)\nax.set_title('Logistic Regression Coefficients (Top/Bottom)', fontweight='bold')\nax.axvline(0, color='black', linewidth=0.5)\nax.set_xlabel('Coefficient')\nplt.tight_layout(); plt.show()")

nb.add_code("# ============================================================\n# Save results\n# ============================================================\nresults_df.to_csv(os.path.join(PROCESSED_DIR, 'model_comparison.csv'))\nprint('✅ Saved: model_comparison.csv')")

nb.add_markdown("---\n\n## Summary\n\n### 🔑 Key Findings:\n\n1. **Random baseline is ~50%** — any model must beat this to add value\n2. **Tree-based models** (RF, XGBoost) generally outperform linear models\n3. **~55% accuracy** is typical for daily direction prediction — the market is efficient!\n4. **Volume and volatility** are the most important features\n5. **TimeSeriesSplit** is essential — random CV would overstate performance by 5-10%\n\n### Model Ranking:\n| Model | Best At | Weakness |\n|-------|---------|----------|\n| Logistic Regression | Interpretability, speed | Linear only |\n| Random Forest | Handles non-linearity | Can overfit |\n| XGBoost | Accuracy, regularization | Complex to tune |\n| LightGBM | Speed, handles large data | Needs tuning |\n\n### Next Steps:\n- **NB09:** Feature selection to reduce overfitting\n- **NB10:** Hyperparameter tuning with Optuna\n- **NB12:** Backtesting to convert predictions into trading strategy\n\n---\n*Next: Notebook 09 — Feature Selection*")

nb.save("notebooks/08_Model_Baseline_Comparison.ipynb")
