from notebook_generator import NotebookBuilder
nb = NotebookBuilder()

nb.add_markdown("# 🎯 Notebook 13: Final Synthesis & Investment Thesis\n\n---\n\n**Author:** Dnyanesh  \n**Date:** February 2025  \n**Series:** Tata Motors Deep Dive (13 of 13)\n\n## Objective\n\nCombine all 12 notebooks' findings into:\n1. **Unified signal** combining ML, sentiment, and technical analysis\n2. **Investment thesis** with conviction score\n3. **Risk assessment** with concrete scenarios\n4. **Self-critique** — what we got wrong and limitations")

nb.add_code("import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nimport os, warnings\nwarnings.filterwarnings('ignore')\nsns.set_style('whitegrid')\nPROCESSED_DIR = '../data/processed'\nprint('✅ Environment ready')")

nb.add_code("# Load all outputs\nfiles = {}\nfor f in ['tata_motors_clean.csv', 'tata_motors_all_features.csv', 'model_comparison.csv', 'prophet_forecast.csv', 'backtest_results.csv', 'strategy_metrics.csv', 'selected_features.csv']:\n    fp = os.path.join(PROCESSED_DIR, f)\n    if os.path.exists(fp):\n        files[f] = pd.read_csv(fp, index_col=0, parse_dates=True) if 'clean' in f or 'features' in f or 'backtest' in f else pd.read_csv(fp, index_col=0)\n        print(f'  ✅ {f}: {files[f].shape}')\n    else:\n        print(f'  ❌ {f}: not found')")

nb.add_markdown("---\n\n## Part 1: 12-Notebook Journey Recap\n\n| NB | Topic | Key Finding |\n|----|-------|------------|\n| 01 | Data Extraction | 5+ years of OHLCV data from yfinance |\n| 02 | Data Cleaning | Missing-value imputation, outlier flagging |\n| 03 | Technical Features | 20+ technical indicators (RSI, MACD, BB) |\n| 04 | Statistical Features | Rolling volatility, z-scores, regime detection |\n| 05 | EDA | Trend regimes identified, Oct 2024 crash analyzed |\n| 06 | Sentiment | News sentiment has weak but measurable correlation |\n| 07 | Clustering | 3-4 market phases identified via K-Means |\n| 08 | Model Comparison | RF/XGBoost ~55% accuracy, beats random |\n| 09 | Feature Selection | Reduced from 30+ to ~15 features |\n| 10 | Hyperparameter Tuning | 1-3% accuracy improvement via Optuna |\n| 11 | Prophet Forecasting | Seasonal patterns + changepoint detection |\n| 12 | Backtesting | ML strategy: better risk-adjusted returns |")

nb.add_code("# Load price data\ndf = files.get('tata_motors_clean.csv', files.get('tata_motors_all_features.csv'))\nif df is not None:\n    close = df['Close']\n    lookback = min(252, len(close))\n    print(f'\\nPrice Range: {close.min():.2f} to {close.max():.2f}')\n    print(f'Current Price: {close.iloc[-1]:.2f}')\n    print(f'{lookback}-day High: {close.iloc[-lookback:].max():.2f}')\n    print(f'{lookback}-day Low:  {close.iloc[-lookback:].min():.2f}')\n    if lookback > 1:\n        print(f'Period Return:   {(close.iloc[-1]/close.iloc[-lookback]-1)*100:+.1f}%')")

nb.add_markdown("---\n\n## Part 2: Signal Integration\n\nWe combine multiple signals into a composite score:\n\n$$\\text{Composite} = w_1 \\cdot S_{\\text{ML}} + w_2 \\cdot S_{\\text{tech}} + w_3 \\cdot S_{\\text{sentiment}} + w_4 \\cdot S_{\\text{trend}}$$")

nb.add_code("signals = {}\n\n# Signal 1: Technical (RSI-based)\nif df is not None and 'RSI_14' in df.columns:\n    rsi = df['RSI_14'].iloc[-1]\n    if rsi < 30: signals['Technical (RSI)'] = {'signal': 'BUY', 'score': 0.8, 'reason': f'RSI={rsi:.0f} (oversold)'}\n    elif rsi > 70: signals['Technical (RSI)'] = {'signal': 'SELL', 'score': -0.8, 'reason': f'RSI={rsi:.0f} (overbought)'}\n    else: signals['Technical (RSI)'] = {'signal': 'NEUTRAL', 'score': (50-rsi)/50, 'reason': f'RSI={rsi:.0f}'}\nelse:\n    signals['Technical (RSI)'] = {'signal': 'N/A', 'score': 0, 'reason': 'RSI not available'}\n\n# Signal 2: Trend (SMA)\nif df is not None:\n    sma_50 = close.rolling(50).mean().iloc[-1]\n    sma_200 = close.rolling(200).mean().iloc[-1]\n    price = close.iloc[-1]\n    if price > sma_50 > sma_200:\n        signals['Trend (SMA)'] = {'signal': 'BULLISH', 'score': 0.6, 'reason': 'Price > SMA50 > SMA200'}\n    elif price < sma_50 < sma_200:\n        signals['Trend (SMA)'] = {'signal': 'BEARISH', 'score': -0.6, 'reason': 'Price < SMA50 < SMA200'}\n    else:\n        signals['Trend (SMA)'] = {'signal': 'MIXED', 'score': 0, 'reason': 'SMAs not aligned'}\n\n# Signal 3: ML Model\nif 'model_comparison.csv' in files:\n    mc = files['model_comparison.csv']\n    best_acc = mc['Accuracy'].max()\n    signals['ML Model'] = {'signal': 'MODERATE', 'score': (best_acc - 0.5)*2, 'reason': f'Best accuracy: {best_acc:.3f}'}\nelse:\n    signals['ML Model'] = {'signal': 'N/A', 'score': 0, 'reason': 'Model results not available'}\n\n# Signal 4: Momentum\nif df is not None:\n    ret_5d = (close.iloc[-1]/close.iloc[-5]-1)*100\n    ret_21d = (close.iloc[-1]/close.iloc[-21]-1)*100\n    momentum_score = np.clip((ret_21d)/20, -1, 1)\n    signals['Momentum'] = {'signal': 'UP' if ret_21d > 0 else 'DOWN', 'score': momentum_score, 'reason': f'5D: {ret_5d:+.1f}%, 21D: {ret_21d:+.1f}%'}\n\nprint('SIGNAL DASHBOARD')\nprint('=' * 60)\nfor name, info in signals.items():\n    print(f'  {name:25s}: {info[\"signal\"]:8s} (score: {info[\"score\"]:+.2f}) — {info[\"reason\"]}')")

nb.add_code("# Composite score\nscores = [s['score'] for s in signals.values()]\ncomposite = np.mean(scores)\nprint(f'\\nCOMPOSITE SIGNAL: {composite:+.3f}')\nif composite > 0.3:\n    verdict = '🟢 BULLISH — Favor long positions'\nelif composite > 0:\n    verdict = '🟡 SLIGHTLY BULLISH — Cautious optimism'\nelif composite > -0.3:\n    verdict = '🟡 SLIGHTLY BEARISH — Reduce exposure'\nelse:\n    verdict = '🔴 BEARISH — Defensive positioning'\nprint(f'Verdict: {verdict}')")

nb.add_code("# Signal radar chart\nfig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))\nlabels = list(signals.keys())\nvalues = [s['score'] for s in signals.values()] + [scores[0]]\nangles = np.linspace(0, 2*np.pi, len(labels), endpoint=False).tolist() + [0]\n\nax.plot(angles, values, 'o-', color='#3498DB', linewidth=2)\nax.fill(angles, values, alpha=0.15, color='#3498DB')\nax.set_xticks(angles[:-1])\nax.set_xticklabels(labels, fontsize=10)\nax.set_ylim(-1, 1)\nax.set_title(f'Signal Radar (Composite: {composite:+.3f})', fontsize=14, fontweight='bold', y=1.08)\nax.axhline(0, color='gray', linestyle='-', alpha=0.3)\nplt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Part 3: Investment Thesis\n\n### Thesis Framework:\n\n| Factor | Assessment | Weight |\n|--------|-----------|--------|\n| **Growth Drivers** | EV transition, JLR turnaround | High |\n| **Risks** | Debt levels, EV competition | Medium |\n| **Valuation** | Relative to sector | Medium |\n| **Technicals** | Current signals | Low |\n| **Sentiment** | Market mood | Low |")

nb.add_code("# Conviction scoring\nprint('INVESTMENT THESIS')\nprint('=' * 60)\n\nfactors = [\n    ('EV Transition Potential', 7, 'Tata is India\\'s EV leader (70%+ market share in EVs)'),\n    ('JLR Turnaround', 6, 'Luxury segment recovering, margins improving'),\n    ('Domestic Market Position', 8, 'Strong brand, growing SUV segment'),\n    ('Debt Concerns', -4, 'High debt-to-equity, but improving'),\n    ('Global Macro Risk', -3, 'EV subsidy uncertainty, commodity prices'),\n    ('Competition Intensity', -5, 'Hyundai, MG, BYD entering India EV'),\n    ('Technical Setup', int(composite*5), f'Composite signal: {composite:+.3f}'),\n]\n\ntotal_positive = sum(s for _, s, _ in factors if s > 0)\ntotal_negative = sum(s for _, s, _ in factors if s < 0)\nnet = total_positive + total_negative\nconviction = min(max(net / 20 * 100, 0), 100)\n\nfor name, score, reason in factors:\n    bar = ('█' * abs(score)) if score >= 0 else ('░' * abs(score))\n    color = '+' if score >= 0 else '-'\n    print(f'  {color} {name:30s}: {score:+3d}  {bar:12s}  {reason}')\n\nprint(f'\\nNet Score: {net:+d}')\nprint(f'Conviction: {conviction:.0f}%')")

nb.add_code("# Conviction gauge\nfig, ax = plt.subplots(figsize=(10, 3))\nax.barh(0, conviction, color='#2ECC71' if conviction > 50 else '#F39C12' if conviction > 30 else '#E74C3C',\n       height=0.5, alpha=0.8)\nax.barh(0, 100, color='#ECF0F1', height=0.5, alpha=0.3)\nax.set_xlim(0, 100)\nax.set_yticks([])\nax.set_title(f'Conviction Meter: {conviction:.0f}%', fontweight='bold', fontsize=14)\nax.axvline(50, color='gray', linestyle='--', alpha=0.5)\nax.text(conviction, 0, f' {conviction:.0f}%', va='center', fontsize=14, fontweight='bold')\nplt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Part 4: Risk Scenarios\n\nWhat could go wrong?")

nb.add_code("print('RISK SCENARIO ANALYSIS')\nprint('=' * 60)\n\nif df is not None:\n    price = close.iloc[-1]\n    vol_ann = close.pct_change().std() * np.sqrt(252)\n    \n    scenarios = [\n        ('🟢 Bull Case', 1.25, 'EV adoption accelerates, JLR margins expand'),\n        ('🟡 Base Case', 1.05, 'Steady growth, sector rotation'),\n        ('🟠 Bear Case', 0.80, 'EV competition intensifies, demand slows'),\n        ('🔴 Tail Risk', 0.55, 'Global recession + credit crisis'),\n    ]\n    \n    print(f'Current Price: ₹{price:.2f}')\n    print(f'Annualized Volatility: {vol_ann*100:.1f}%\\n')\n    \n    for label, mult, reason in scenarios:\n        target = price * mult\n        ret = (mult - 1) * 100\n        print(f'{label}: ₹{target:,.0f} ({ret:+.0f}%)')\n        print(f'  Rationale: {reason}\\n')")

nb.add_code("# Risk visualization\nif df is not None:\n    fig, ax = plt.subplots(figsize=(14, 6))\n    ax.plot(close.index[-lookback:], close.iloc[-lookback:], color='#2C3E50', linewidth=2, label='Actual Price')\n    \n    last_date = close.index[-1]\n    for label, mult, color_s in [('Bull', 1.25, '#2ECC71'), ('Base', 1.05, '#3498DB'),\n                                ('Bear', 0.80, '#F39C12'), ('Tail', 0.55, '#E74C3C')]:\n        ax.axhline(price*mult, color=color_s, linestyle='--', alpha=0.6, label=f'{label}: ₹{price*mult:,.0f}')\n    \n    ax.set_title('Price Scenarios (12-Month)', fontweight='bold', fontsize=14)\n    ax.legend(loc='upper left', fontsize=10)\n    ax.grid(True, alpha=0.3)\n    plt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Part 5: Self-Critique & Limitations\n\nEvery analysis has blind spots. Here's an honest assessment:")

nb.add_code("print('LIMITATIONS & SELF-CRITIQUE')\nprint('=' * 60)\n\nlimitations = [\n    ('Survivorship Bias', 'We only analyzed Tata Motors because it survived. Failed companies are invisible.'),\n    ('Data Snooping', 'Testing many features on the same data increases false discoveries.'),\n    ('Look-Ahead Bias', 'Despite TimeSeriesSplit, feature engineering uses full history.'),\n    ('No Transaction Costs', 'Real costs Brokerage, impact cost, slippage are higher.'),\n    ('Single Stock', 'No portfolio diversification analysis.'),\n    ('Regime Change', 'Models trained on past regimes may fail in new ones.'),\n    ('Sentiment Data Quality', 'News scraping is noisy and incomplete.'),\n    ('No Fundamental Analysis', 'P/E, debt ratios, management quality not included.'),\n]\n\nfor i, (title, detail) in enumerate(limitations):\n    print(f'  {i+1}. [{title}]')\n    print(f'     {detail}\\n')")

nb.add_code("# What would we do differently?\nprint('WHAT WE WOULD DO DIFFERENTLY')\nprint('=' * 60)\nimprovements = [\n    'Use alternative data (satellite, social media, insider trading)',\n    'Try deep learning (LSTM, Transformer) for sequence modeling',\n    'Add fundamental data (quarterly earnings, balance sheet)',\n    'Build a portfolio instead of single-stock analysis',\n    'Use intraday data for more granular signals',\n    'Implement proper walk-forward with purged cross-validation',\n    'Add options-derived features (implied volatility, put-call ratio)',\n]\nfor i, imp in enumerate(improvements):\n    print(f'  {i+1}. {imp}')")

nb.add_markdown("---\n\n## Part 6: Final Dashboard")

nb.add_code("# Final summary dashboard\nfig, axes = plt.subplots(2, 2, figsize=(16, 12))\n\n# 1. Price chart with SMAs\nax = axes[0,0]\nif df is not None:\n    ax.plot(close.index[-lookback:], close.iloc[-lookback:], color='#2C3E50', linewidth=1.5, label='Close')\n    sma50 = close.rolling(50).mean()\n    sma200 = close.rolling(200).mean()\n    ax.plot(sma50.index[-lookback:], sma50.iloc[-lookback:], color='#3498DB', linewidth=1, label='SMA 50')\n    ax.plot(sma200.index[-lookback:], sma200.iloc[-lookback:], color='#E74C3C', linewidth=1, label='SMA 200')\n    ax.set_title('Price & Moving Averages', fontweight='bold')\n    ax.legend(fontsize=9)\n\n# 2. Return distribution\nax = axes[0,1]\nif df is not None:\n    rets = close.pct_change().dropna()\n    ax.hist(rets*100, bins=50, color='#3498DB', alpha=0.7, edgecolor='white')\n    ax.axvline(0, color='black', linewidth=1)\n    ax.axvline(rets.mean()*100, color='red', linestyle='--', label=f'Mean: {rets.mean()*100:.3f}%')\n    ax.set_title('Daily Return Distribution', fontweight='bold')\n    ax.set_xlabel('Return (%)'); ax.legend()\n\n# 3. Signal composite\nax = axes[1,0]\nsig_names = list(signals.keys())\nsig_scores = [s['score'] for s in signals.values()]\ncolors_s = ['#2ECC71' if s > 0 else '#E74C3C' for s in sig_scores]\nax.barh(sig_names, sig_scores, color=colors_s, alpha=0.8)\nax.axvline(0, color='black', linewidth=0.5)\nax.set_title(f'Signal Dashboard (Composite: {composite:+.3f})', fontweight='bold')\n\n# 4. Model accuracy\nax = axes[1,1]\nif 'model_comparison.csv' in files:\n    mc = files['model_comparison.csv']\n    mc['Accuracy'].plot(kind='barh', ax=ax, color='#F39C12', alpha=0.8)\n    ax.axvline(0.5, color='red', linestyle='--', alpha=0.5, label='Random')\n    ax.set_title('Model Accuracy Comparison', fontweight='bold')\n    ax.legend()\nelse:\n    ax.text(0.5, 0.5, 'Model results\\nnot available', ha='center', va='center', fontsize=14)\n    ax.set_title('Model Accuracy', fontweight='bold')\n\nplt.suptitle('TATA MOTORS — FINAL ANALYSIS DASHBOARD', fontsize=16, fontweight='bold', y=1.01)\nplt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Conclusion\n\n### Verdict:\n\nTata Motors represents a **compelling but volatile** investment opportunity:\n\n**FOR:**\n- India's EV market leader with first-mover advantage\n- JLR turnaround providing luxury segment earnings\n- Strong domestic brand in growing SUV segment\n\n**AGAINST:**\n- High debt levels constrain flexibility\n- Intense EV competition from Chinese manufacturers (BYD)\n- Global macro uncertainty affects luxury demand\n\n**Our ML Analysis Adds:**\n- ~55% directional accuracy — marginally better than random\n- Prophet shows seasonal price patterns that can inform entry/exit timing\n- Backtesting suggests ML-guided risk management reduces drawdowns\n- Feature selection reveals volume and volatility as key predictive signals\n\n### Final Recommendation:\n\n> **Moderate HOLD with tactical trading overlay.** Use ML signals to adjust position size (not for binary buy/sell decisions). Combine with fundamental analysis for a complete picture.\n\n### Confidence Level: MODERATE\n\nThe stock market is inherently unpredictable. All models are wrong; some are useful.\n\n---\n\n*🎓 End of Tata Motors Deep Dive Series*")

nb.save("notebooks/13_Final_Synthesis.ipynb")
