from notebook_generator import NotebookBuilder
nb = NotebookBuilder()

# Cell 1
nb.add_markdown("# 📊 Notebook 05: Exploratory Data Analysis — Trends & Regimes\n\n---\n\n**Author:** Dnyanesh  \n**Date:** February 2025  \n**series:** Tata Motors Deep Dive (5 of 13)\n\n## Objective\n\nThis notebook is the **visual storytelling** chapter of our analysis. We move beyond raw numbers to uncover:\n1. **Distribution patterns** in Tata Motors' returns\n2. **Regime-level performance** comparison (Pre-COVID → Post-COVID → Oct 2024)\n3. **Cross-stock analysis** (vs Maruti, M&M, NIFTY50)\n4. **Volume anomalies** and their price implications\n5. **Deep dive** into the October 2024 crash\n\n> *\"The goal is to turn data into information, and information into insight.\"* — Carly Fiorina")

# Cell 2
nb.add_code("# ============================================================\n# Setup & Configuration\n# ============================================================\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport matplotlib.gridspec as gridspec\nimport seaborn as sns\nfrom scipy import stats\nimport os, warnings\nwarnings.filterwarnings('ignore')\n\n# Style configuration\nsns.set_style('whitegrid')\nplt.rcParams['figure.figsize'] = (16, 8)\nplt.rcParams['font.size'] = 12\nplt.rcParams['axes.titlesize'] = 14\nplt.rcParams['axes.labelsize'] = 12\n\nPROCESSED_DIR = '../data/processed'\nprint('✅ Environment ready')\nprint(f'📁 Data directory: {PROCESSED_DIR}')")

# Cell 3
nb.add_code("# ============================================================\n# Load datasets\n# ============================================================\ndf = pd.read_csv(os.path.join(PROCESSED_DIR, 'tata_motors_clean.csv'), index_col=0, parse_dates=True)\n\n# Try loading peer stocks\ntry:\n    merged = pd.read_csv(os.path.join(PROCESSED_DIR, 'merged_all_stocks.csv'), index_col=0, parse_dates=True)\n    PEERS_OK = True\nexcept:\n    PEERS_OK = False\n\nprint(f'Tata Motors: {df.shape[0]} trading days')\nprint(f'Date range: {df.index.min().date()} to {df.index.max().date()}')\nif PEERS_OK:\n    print(f'Peer data: {merged.shape}')")

# Cell 4
nb.add_markdown("---\n\n## Part 1: Univariate Analysis — Understanding the Price\n\n### 1.1 Price History Overview\n\nBefore any statistical tests, let's LOOK at the data. A time series plot reveals trends, volatility clusters, and structural breaks that numbers alone cannot.")

# Cell 5
nb.add_code("# ============================================================\n# 1.1 Complete Price History\n# ============================================================\nfig, ax = plt.subplots(figsize=(18, 8))\n\nax.plot(df.index, df['Close'], color='#2C3E50', linewidth=1.5, label='Close Price')\n\n# Add moving averages\nma50 = df['Close'].rolling(50).mean()\nma200 = df['Close'].rolling(200).mean()\nax.plot(df.index, ma50, color='#E74C3C', linewidth=1, alpha=0.7, label='50-day MA')\nax.plot(df.index, ma200, color='#3498DB', linewidth=1, alpha=0.7, label='200-day MA')\n\n# Highlight key events\nax.axvline(pd.Timestamp('2020-03-23'), color='red', linestyle='--', alpha=0.5, label='COVID Crash')\nax.axvline(pd.Timestamp('2024-10-09'), color='purple', linestyle='--', alpha=0.5, label='Oct 2024 Event')\n\nax.fill_between(df.index, df['Low'], df['High'], alpha=0.05, color='gray')\nax.set_title('Tata Motors — Complete Price History with Key Events', fontsize=16, fontweight='bold')\nax.set_ylabel('Price (₹)')\nax.legend(loc='upper left', fontsize=10)\nax.grid(True, alpha=0.3)\nplt.tight_layout(); plt.show()")

# Cell 6
nb.add_markdown("**Interpretation:** The price chart reveals several distinct phases:\n- **2019-2020:** Steady decline before COVID\n- **March 2020:** Sharp COVID crash (bottomed around ₹70)\n- **2020-2024:** Remarkable recovery, 10x+ returns\n- **October 2024:** Sudden sharp decline\n\nThe MA crossovers (golden cross/death cross) have historically been reliable regime change signals.")

# Cell 7
nb.add_code("# ============================================================\n# 1.2 Daily Returns Calculation\n# ============================================================\nif 'Log_Return' not in df.columns:\n    df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))\nif 'Simple_Return' not in df.columns:\n    df['Simple_Return'] = df['Close'].pct_change()\n\nprint('Return Statistics:')\nprint(f'  Mean daily return:    {df[\"Log_Return\"].mean()*100:.4f}%')\nprint(f'  Median daily return:  {df[\"Log_Return\"].median()*100:.4f}%')\nprint(f'  Std deviation:        {df[\"Log_Return\"].std()*100:.4f}%')\nprint(f'  Annualized return:    {df[\"Log_Return\"].mean()*252*100:.2f}%')\nprint(f'  Annualized volatility:{df[\"Log_Return\"].std()*np.sqrt(252)*100:.2f}%')\nprint(f'\\nBest day:  {df[\"Log_Return\"].max()*100:.2f}% on {df[\"Log_Return\"].idxmax().date()}')\nprint(f'Worst day: {df[\"Log_Return\"].min()*100:.2f}% on {df[\"Log_Return\"].idxmin().date()}')")

# Cell 8
nb.add_markdown("### 1.2 Return Distribution\n\nIf returns were perfectly normal (Gaussian), we could predict extremes easily. Financial returns are almost never normal — they have **fat tails** (extreme events happen more often than expected) and **negative skew** (crashes are sharper than rallies).\n\n$$\\text{Skewness} = \\frac{E[(X-\\mu)^3]}{\\sigma^3}$$\n$$\\text{Kurtosis} = \\frac{E[(X-\\mu)^4]}{\\sigma^4}$$\n\n- Skewness < 0 → Left tail is longer (more crash risk)\n- Kurtosis > 3 → Fatter tails than normal (leptokurtic)")

# Cell 9
nb.add_code("# ============================================================\n# Return distribution analysis\n# ============================================================\nret = df['Log_Return'].dropna()\n\nfig, axes = plt.subplots(1, 3, figsize=(20, 6))\n\n# Histogram with normal overlay\nax = axes[0]\nax.hist(ret, bins=100, density=True, alpha=0.7, color='#3498DB', edgecolor='white', label='Actual')\nx = np.linspace(ret.min(), ret.max(), 100)\nax.plot(x, stats.norm.pdf(x, ret.mean(), ret.std()), 'r-', linewidth=2, label='Normal Fit')\nax.set_title('Return Distribution vs Normal', fontweight='bold')\nax.set_xlabel('Daily Log Return')\nax.legend()\n\n# QQ Plot\nax = axes[1]\nstats.probplot(ret, dist='norm', plot=ax)\nax.set_title('Q-Q Plot (Normal)', fontweight='bold')\nax.get_lines()[0].set_color('#3498DB')\n\n# Box plot\nax = axes[2]\nbp = ax.boxplot(ret, vert=True, patch_artist=True)\nbp['boxes'][0].set_facecolor('#3498DB')\nbp['boxes'][0].set_alpha(0.7)\nax.set_title('Box Plot', fontweight='bold')\nax.set_ylabel('Daily Log Return')\n\nplt.tight_layout(); plt.show()")

# Cell 10
nb.add_code("# Statistical tests for normality\nprint('NORMALITY TESTS')\nprint('=' * 50)\n\nskew = stats.skew(ret)\nkurt = stats.kurtosis(ret)  # excess kurtosis\nprint(f'Skewness:         {skew:.4f} {\"(negative — crash risk)\" if skew < 0 else \"(positive)\"}')\nprint(f'Excess Kurtosis:  {kurt:.4f} {\"(fat tails!)\" if kurt > 0 else \"\"}')\n\n# Jarque-Bera test\njb_stat, jb_pval = stats.jarque_bera(ret)\nprint(f'\\nJarque-Bera test: stat={jb_stat:.2f}, p-value={jb_pval:.2e}')\nprint(f'  → Returns are {\"NOT\" if jb_pval < 0.05 else \"\"} normally distributed (p={jb_pval:.4f})')\n\n# Shapiro-Wilk (on subset for speed)\nif len(ret) > 5000:\n    sw_stat, sw_pval = stats.shapiro(ret.sample(5000, random_state=42))\nelse:\n    sw_stat, sw_pval = stats.shapiro(ret)\nprint(f'Shapiro-Wilk:     stat={sw_stat:.4f}, p-value={sw_pval:.2e}')")

# Cell 11
nb.add_markdown("**Key Finding:** Returns are significantly non-normal. The Q-Q plot shows clear deviation in the tails, and both Jarque-Bera and Shapiro-Wilk reject normality at the 1% level. This means:\n- VaR calculations assuming normality will UNDERESTIMATE risk\n- Extreme losses (>3σ) happen more often than expected\n- Options pricing models (Black-Scholes) may be inaccurate")

# Cell 12
nb.add_markdown("---\n\n## Part 2: Regime Analysis\n\n### 2.1 Defining Market Regimes\n\nWe segment the timeline into distinct \"regimes\" based on key market events:\n\n| Regime | Period | Context |\n|--------|--------|---------|\n| Pre-COVID | Before Mar 2020 | Normal market conditions |\n| COVID Crash | Mar-Apr 2020 | Pandemic panic selling |\n| Recovery | May 2020 - Dec 2021 | Post-crash rally |\n| Post-COVID | Jan 2022 - Sep 2024 | Consolidation & growth |\n| Oct 2024 Crash | Oct 2024+ | Ratan Tata passing event |")

# Cell 13
nb.add_code("# ============================================================\n# Define regimes\n# ============================================================\ndef assign_regime(date):\n    if date < pd.Timestamp('2020-03-01'):\n        return 'Pre-COVID'\n    elif date < pd.Timestamp('2020-05-01'):\n        return 'COVID Crash'\n    elif date < pd.Timestamp('2022-01-01'):\n        return 'Recovery'\n    elif date < pd.Timestamp('2024-10-01'):\n        return 'Post-COVID'\n    else:\n        return 'Oct 2024 Crash'\n\ndf['Regime'] = df.index.map(assign_regime)\n\nprint('Regime Distribution:')\nfor regime in ['Pre-COVID', 'COVID Crash', 'Recovery', 'Post-COVID', 'Oct 2024 Crash']:\n    count = (df['Regime'] == regime).sum()\n    pct = count / len(df) * 100\n    print(f'  {regime:20s}: {count:4d} days ({pct:.1f}%)')")

# Cell 14
nb.add_code("# ============================================================\n# 2.2 Regime-wise return statistics\n# ============================================================\nregime_stats = []\nfor regime in ['Pre-COVID', 'COVID Crash', 'Recovery', 'Post-COVID', 'Oct 2024 Crash']:\n    mask = df['Regime'] == regime\n    r = df.loc[mask, 'Log_Return'].dropna()\n    if len(r) < 5:\n        continue\n    regime_stats.append({\n        'Regime': regime,\n        'Days': len(r),\n        'Mean (%)': f'{r.mean()*100:.4f}',\n        'Std (%)': f'{r.std()*100:.4f}',\n        'Ann Return (%)': f'{r.mean()*252*100:.1f}',\n        'Ann Vol (%)': f'{r.std()*np.sqrt(252)*100:.1f}',\n        'Sharpe': f'{r.mean()/r.std()*np.sqrt(252):.2f}' if r.std() > 0 else 'N/A',\n        'Skewness': f'{stats.skew(r):.3f}',\n        'Max Drawdown (%)': f'{((1+r).cumprod()/(1+r).cumprod().expanding().max()-1).min()*100:.1f}'\n    })\n\nprint(pd.DataFrame(regime_stats).to_string(index=False))")

# Cell 15
nb.add_markdown("**Regime Comparison Insights:**\n- **Recovery** regime has the highest annualized return (10x rally!)\n- **COVID Crash** has highest volatility but was brief\n- **Oct 2024** shows elevated volatility with negative returns\n- The Sharpe ratio tells us risk-adjusted performance — not just returns")

# Cell 16
nb.add_code("# ============================================================\n# 2.3 Regime return distributions\n# ============================================================\nfig, axes = plt.subplots(2, 3, figsize=(18, 10))\naxes = axes.flatten()\n\ncolors = {'Pre-COVID': '#3498DB', 'COVID Crash': '#E74C3C', 'Recovery': '#2ECC71',\n          'Post-COVID': '#F39C12', 'Oct 2024 Crash': '#8E44AD'}\n\nfor i, (regime, color) in enumerate(colors.items()):\n    if i >= len(axes):\n        break\n    ax = axes[i]\n    mask = df['Regime'] == regime\n    r = df.loc[mask, 'Log_Return'].dropna()\n    if len(r) > 0:\n        ax.hist(r, bins=50, color=color, alpha=0.7, edgecolor='white', density=True)\n        ax.axvline(r.mean(), color='black', linestyle='--', linewidth=1.5, label=f'Mean: {r.mean()*100:.3f}%')\n        ax.set_title(f'{regime}\\n(n={len(r)} days)', fontweight='bold')\n        ax.legend(fontsize=9)\n\n# Hide extra subplot\naxes[5].set_visible(False)\nplt.suptitle('Return Distributions by Regime', fontsize=16, fontweight='bold', y=1.02)\nplt.tight_layout(); plt.show()")

# Cell 17
nb.add_code("# ============================================================\n# 2.4 Regime box plot comparison\n# ============================================================\nfig, ax = plt.subplots(figsize=(14, 6))\n\nregime_data = []\nregime_labels = []\nfor regime in ['Pre-COVID', 'COVID Crash', 'Recovery', 'Post-COVID', 'Oct 2024 Crash']:\n    mask = df['Regime'] == regime\n    r = df.loc[mask, 'Log_Return'].dropna()\n    if len(r) > 0:\n        regime_data.append(r.values)\n        regime_labels.append(regime)\n\nbp = ax.boxplot(regime_data, labels=regime_labels, patch_artist=True, showmeans=True,\n               meanprops={'marker':'o','markerfacecolor':'white','markeredgecolor':'black'})\n\nfor patch, label in zip(bp['boxes'], regime_labels):\n    patch.set_facecolor(colors.get(label, 'gray'))\n    patch.set_alpha(0.6)\n\nax.set_title('Return Distribution by Regime (Box Plot)', fontweight='bold')\nax.set_ylabel('Daily Log Return')\nax.axhline(0, color='black', linestyle='-', alpha=0.3)\nax.tick_params(axis='x', rotation=15)\nplt.tight_layout(); plt.show()")

# Cell 18
nb.add_markdown("---\n\n## Part 3: Price–Volume Dynamics\n\n### 3.1 Volume Analysis\n\nVolume confirms price moves. High volume on a price decline = strong selling conviction. Low volume on a rally = weak, unsustainable move.")

# Cell 19
nb.add_code("# ============================================================\n# 3.1 Volume trend\n# ============================================================\nfig, axes = plt.subplots(2, 1, figsize=(18, 10), gridspec_kw={'height_ratios': [2, 1]})\n\n# Price\nax = axes[0]\nax.plot(df.index, df['Close'], color='#2C3E50', linewidth=1.5)\nax.set_title('Price & Volume', fontsize=14, fontweight='bold')\nax.set_ylabel('Price (₹)')\n\n# Volume\nax = axes[1]\nif 'Volume' in df.columns:\n    vol_colors = ['#2ECC71' if r > 0 else '#E74C3C' for r in df['Log_Return'].fillna(0)]\n    ax.bar(df.index, df['Volume']/1e6, color=vol_colors, alpha=0.5, width=1)\n    ax.plot(df.index, (df['Volume']/1e6).rolling(20).mean(), color='black', linewidth=1, label='20-day avg')\n    ax.set_ylabel('Volume (Millions)')\n    ax.legend()\n\nplt.tight_layout(); plt.show()")

# Cell 20
nb.add_code("# ============================================================\n# 3.2 Volume spike detection\n# ============================================================\nif 'Volume' in df.columns:\n    vol_mean = df['Volume'].rolling(20).mean()\n    vol_std = df['Volume'].rolling(20).std()\n    df['Volume_ZScore'] = (df['Volume'] - vol_mean) / vol_std\n    \n    # Volume spikes (> 2 standard deviations)\n    spikes = df[df['Volume_ZScore'] > 2].copy()\n    \n    print(f'Volume Spikes (>2σ): {len(spikes)} days out of {len(df)}')\n    print(f'\\nTop 10 Volume Spikes:')\n    top_spikes = spikes.nlargest(10, 'Volume_ZScore')\n    for idx, row in top_spikes.iterrows():\n        ret = row['Log_Return'] * 100 if 'Log_Return' in row else 0\n        print(f'  {idx.date()} | Volume Z: {row[\"Volume_ZScore\"]:.1f} | Return: {ret:+.2f}%')")

# Cell 21
nb.add_markdown("**Volume Interpretation:**\n- Volume spikes often coincide with major news events\n- The highest volume days correspond to earnings releases and macro events\n- The Oct 2024 period shows elevated volume — confirming panic selling")

# Cell 22
nb.add_code("# ============================================================\n# 3.3 Price-Volume Correlation\n# ============================================================\nif 'Volume' in df.columns:\n    fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n    \n    ax = axes[0]\n    ax.scatter(df['Volume']/1e6, df['Log_Return'].abs()*100, alpha=0.3, s=10, color='#3498DB')\n    ax.set_xlabel('Volume (Millions)')\n    ax.set_ylabel('|Daily Return| (%)')\n    ax.set_title('Volume vs Absolute Return', fontweight='bold')\n    corr = df['Volume'].corr(df['Log_Return'].abs())\n    ax.text(0.05, 0.95, f'r = {corr:.3f}', transform=ax.transAxes, fontsize=12,\n            verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))\n    \n    ax = axes[1]\n    for regime, color in colors.items():\n        mask = df['Regime'] == regime\n        if mask.sum() > 0:\n            ax.scatter(df.loc[mask, 'Volume']/1e6, df.loc[mask, 'Log_Return']*100,\n                      alpha=0.3, s=10, color=color, label=regime)\n    ax.set_xlabel('Volume (Millions)')\n    ax.set_ylabel('Daily Return (%)')\n    ax.set_title('Volume vs Return (by Regime)', fontweight='bold')\n    ax.legend(fontsize=8, markerscale=3)\n    \n    plt.tight_layout(); plt.show()")

# Cell 23
nb.add_markdown("---\n\n## Part 4: Cross-Stock Comparison\n\n### 4.1 Tata Motors vs Peers\n\nIs Tata Motors' behavior unique, or do all auto stocks move similarly? Comparing with:\n- **Maruti Suzuki** — India's largest car maker\n- **Mahindra & Mahindra** — Direct competitor (also in EVs)\n- **Bajaj Auto** — Broader auto sector control (two-wheeler specialist)\n- **Ashok Leyland** — Direct TMCV commercial vehicle competitor\n- **Hyundai Motor India** — Direct TMPV passenger vehicle competitor (Oct 2024 IPO)\n- **Toyota Motor** — Global auto bellwether\n- **Volkswagen AG** — European EV transition parallel\n- **NIFTY 50** — Broad market benchmark\n- **NIFTY Auto** — Sector benchmark")

# Cell 24
nb.add_code("# ============================================================\n# 4.1 Cumulative return comparison\n# ============================================================\nif PEERS_OK:\n    # Find price columns\n    price_cols = [c for c in merged.columns if 'Close' in c]\n    if not price_cols:\n        price_cols = [c for c in merged.columns if any(s in c for s in ['TATA', 'MARUTI', 'M&M', 'NIFTY'])]\n    \n    if price_cols:\n        fig, ax = plt.subplots(figsize=(18, 8))\n        colors_list = ['#2C3E50', '#E74C3C', '#2ECC71', '#3498DB', '#F39C12',\n                       '#9B59B6', '#1ABC9C', '#E67E22', '#34495E', '#16A085', '#C0392B']\n        \n        for i, col in enumerate(price_cols):\n            norm = merged[col] / merged[col].dropna().iloc[0] * 100\n            ax.plot(merged.index, norm, label=col, linewidth=1.5, color=colors_list[i % len(colors_list)])\n        \n        ax.axhline(100, color='gray', linestyle=':', alpha=0.5)\n        ax.set_title('Normalized Price Comparison (Base = 100)', fontsize=14, fontweight='bold')\n        ax.set_ylabel('Indexed Value')\n        ax.legend(fontsize=9, ncol=2)\n        ax.grid(True, alpha=0.3)\n        plt.tight_layout(); plt.show()\nelse:\n    print('Peer data not available. Skipping cross-stock comparison.')")

# Cell 25
nb.add_code("# ============================================================\n# 4.2 Correlation matrix\n# ============================================================\nif PEERS_OK and price_cols:\n    returns_df = merged[price_cols].pct_change().dropna()\n    \n    n_assets = len(returns_df.columns)\n    fig_w = max(10, n_assets*1.1); fig_h = max(8, n_assets*0.9)\n    fig, ax = plt.subplots(figsize=(fig_w, fig_h))\n    corr = returns_df.corr()\n    sns.heatmap(corr, annot=True, fmt='.2f', cmap='RdYlGn', center=0,\n               ax=ax, linewidths=1, square=True, vmin=-1, vmax=1, annot_kws={'size':8})\n    ax.set_title(f'Return Correlation Matrix ({n_assets} Assets)', fontweight='bold')\n    ax.tick_params(axis='both', labelsize=8, rotation=45)\n    plt.tight_layout(); plt.show()\n    \n    print('\\\\nCorrelation Insights:')\n    for i in range(len(corr.columns)):\n        for j in range(i+1, len(corr.columns)):\n            print(f'  {corr.columns[i]:25s} <-> {corr.columns[j]:25s}: {corr.iloc[i,j]:.3f}')")

# Cell 26
nb.add_markdown("**Cross-Stock Insight:**\n- High correlation with NIFTY Auto confirms Tata Motors moves with the sector\n- M&M and Ashok Leyland provide the closest peer comparisons (SUV/CV respectively)\n- Toyota/VW correlation captures global auto cycle exposure (JLR sensitivity)\n- Correlation spikes during market stress (COVID, Oct 2024) — \"correlations go to 1 in a crisis\"\n- Unique company-specific events create temporary decorrelation")

# Cell 27
nb.add_code("# ============================================================\n# 4.3 Rolling correlation (vs all peers)\n# ============================================================\nif PEERS_OK and len(price_cols) >= 2:\n    fig, ax = plt.subplots(figsize=(18, 7))\n    tata_col = price_cols[0]\n    ret1 = merged[tata_col].pct_change()\n    peer_colors = ['#E74C3C','#2ECC71','#F39C12','#9B59B6','#1ABC9C',\n                   '#E67E22','#34495E','#16A085','#C0392B','#3498DB']\n    \n    for i, col in enumerate(price_cols[1:]):\n        ret2 = merged[col].pct_change()\n        rolling_corr = ret1.rolling(63).corr(ret2)\n        ax.plot(merged.index, rolling_corr, label=col, linewidth=1, alpha=0.7,\n                color=peer_colors[i % len(peer_colors)])\n    \n    ax.axhline(0, color='black', linestyle='-', alpha=0.3)\n    ax.set_title('Rolling 63-day Correlation with Tata Motors', fontweight='bold', fontsize=14)\n    ax.set_ylabel('Correlation')\n    ax.legend(fontsize=8, ncol=2)\n    ax.set_ylim(-0.5, 1.0)\n    ax.grid(True, alpha=0.3)\n    plt.tight_layout(); plt.show()")

# Cell 28
nb.add_markdown("---\n\n## Part 5: October 2024 Deep Dive\n\n### 5.1 The Event\n\nOn October 9, 2024, Ratan Tata — the legendary chairman of Tata Group — passed away at age 86. The event triggered:\n- **Emotional selling** across Tata Group stocks\n- **Volume spikes** 3-5x above normal\n- **Cross-sector contagion** (all Tata stocks declined)")

# Cell 29
nb.add_code("# ============================================================\n# 5.1 Oct 2024 Price Action Zoom\n# ============================================================\nstart_date = pd.Timestamp('2024-09-15')\nend_date = pd.Timestamp('2024-11-15')\nevent_date = pd.Timestamp('2024-10-09')\n\nmask = (df.index >= start_date) & (df.index <= end_date)\noct_df = df[mask].copy()\n\nif len(oct_df) > 0:\n    fig, axes = plt.subplots(3, 1, figsize=(18, 14), gridspec_kw={'height_ratios': [3, 1, 1]})\n    \n    # Price\n    ax = axes[0]\n    ax.plot(oct_df.index, oct_df['Close'], color='#2C3E50', linewidth=2)\n    ax.fill_between(oct_df.index, oct_df['Low'], oct_df['High'], alpha=0.15, color='gray')\n    if event_date in oct_df.index or any(oct_df.index == event_date):\n        ax.axvline(event_date, color='red', linestyle='--', linewidth=2, label='Event: Oct 9')\n    ax.set_title('October 2024 — Price Action Detail', fontsize=14, fontweight='bold')\n    ax.set_ylabel('Price (₹)'); ax.legend(fontsize=11)\n    \n    # Volume\n    ax = axes[1]\n    if 'Volume' in oct_df.columns:\n        vol_colors = ['#2ECC71' if r > 0 else '#E74C3C' for r in oct_df['Log_Return'].fillna(0)]\n        ax.bar(oct_df.index, oct_df['Volume']/1e6, color=vol_colors, alpha=0.7)\n    ax.set_ylabel('Volume (M)')\n    ax.set_title('Volume')\n    \n    # Daily returns\n    ax = axes[2]\n    colors_ret = ['#2ECC71' if r > 0 else '#E74C3C' for r in oct_df['Log_Return'].fillna(0)]\n    ax.bar(oct_df.index, oct_df['Log_Return']*100, color=colors_ret, alpha=0.7)\n    ax.set_ylabel('Daily Return (%)')\n    ax.set_title('Daily Returns')\n    \n    plt.tight_layout(); plt.show()\nelse:\n    print('Oct 2024 data not available in dataset')")

# Cell 30
nb.add_code("# ============================================================\n# 5.2 Oct 2024 in numbers\n# ============================================================\nif len(oct_df) > 0 and 'Log_Return' in oct_df.columns:\n    oct_returns = oct_df['Log_Return'].dropna()\n    \n    # Pre-event vs post-event\n    pre_event = oct_df[oct_df.index < event_date]\n    post_event = oct_df[oct_df.index >= event_date]\n    \n    print('OCT 2024 DEEP DIVE')\n    print('=' * 50)\n    print(f'\\nPre-event (Sep 15 - Oct 8):')\n    if len(pre_event) > 0:\n        print(f'  Peak price:    ₹{pre_event[\"Close\"].max():.2f}')\n        print(f'  Avg volume:    {pre_event[\"Volume\"].mean()/1e6:.1f}M' if 'Volume' in pre_event else '')\n    \n    print(f'\\nPost-event (Oct 9+):')\n    if len(post_event) > 0:\n        print(f'  Low price:     ₹{post_event[\"Close\"].min():.2f}')\n        print(f'  Max drawdown:  {(post_event[\"Close\"].min()/pre_event[\"Close\"].max()-1)*100:.1f}%' if len(pre_event) > 0 else '')\n        print(f'  Avg volume:    {post_event[\"Volume\"].mean()/1e6:.1f}M' if 'Volume' in post_event else '')\n        print(f'  Volume spike:  {post_event[\"Volume\"].mean()/pre_event[\"Volume\"].mean():.1f}x above pre-event' if 'Volume' in post_event and len(pre_event) > 0 else '')\n        print(f'  Recovery days: {len(post_event)}')")

# Cell 31
nb.add_markdown("### 5.2 Oct 2024 vs COVID Crash Comparison\n\nHow does the Oct 2024 decline compare to the COVID crash?")

# Cell 32
nb.add_code("# ============================================================\n# Compare Oct 2024 vs COVID\n# ============================================================\ncovid_mask = (df.index >= pd.Timestamp('2020-02-15')) & (df.index <= pd.Timestamp('2020-05-01'))\ncovid_df = df[covid_mask]\n\nif len(covid_df) > 0 and len(oct_df) > 0:\n    covid_ret = covid_df['Log_Return'].dropna()\n    oct_ret = oct_df['Log_Return'].dropna()\n    \n    comparison = pd.DataFrame({\n        'Metric': ['Duration (days)', 'Max Single-Day Loss (%)', 'Total Decline (%)',\n                   'Avg Daily Vol (%)', 'Max Volume Spike', 'Recovery Time'],\n        'COVID Crash': [\n            len(covid_df),\n            f'{covid_ret.min()*100:.2f}',\n            f'{(covid_df[\"Close\"].iloc[-1]/covid_df[\"Close\"].iloc[0]-1)*100:.1f}',\n            f'{covid_ret.std()*100:.3f}',\n            f'{covid_df[\"Volume\"].max()/covid_df[\"Volume\"].mean():.1f}x' if 'Volume' in covid_df else 'N/A',\n            'Months'\n        ],\n        'Oct 2024': [\n            len(oct_df),\n            f'{oct_ret.min()*100:.2f}',\n            f'{(oct_df[\"Close\"].iloc[-1]/oct_df[\"Close\"].iloc[0]-1)*100:.1f}',\n            f'{oct_ret.std()*100:.3f}',\n            f'{oct_df[\"Volume\"].max()/oct_df[\"Volume\"].mean():.1f}x' if 'Volume' in oct_df else 'N/A',\n            'Weeks'\n        ]\n    })\n    print(comparison.to_string(index=False))")

# Cell 33
nb.add_markdown("**COVID vs Oct 2024:**\n- COVID was a broader, deeper market crash affecting ALL stocks\n- Oct 2024 was a company/group-specific event\n- COVID recovery took months; Oct 2024 recovery was faster\n- Volume patterns differ: COVID showed sustained high volume, Oct 2024 was a spike")

# Cell 34
nb.add_markdown("---\n\n## Part 6: Additional Statistical Tests")

# Cell 35
nb.add_code("# ============================================================\n# 6.1 Autocorrelation of returns\n# ============================================================\nfrom statsmodels.graphics.tsaplots import plot_acf, plot_pacf\nfrom statsmodels.stats.diagnostic import acorr_ljungbox\n\nfig, axes = plt.subplots(1, 2, figsize=(16, 5))\n\nret_clean = df['Log_Return'].dropna()\n\ntry:\n    plot_acf(ret_clean, lags=30, ax=axes[0], alpha=0.05)\n    axes[0].set_title('Autocorrelation (Returns)', fontweight='bold')\n    \n    plot_acf(ret_clean**2, lags=30, ax=axes[1], alpha=0.05)\n    axes[1].set_title('Autocorrelation (Squared Returns)', fontweight='bold')\nexcept:\n    axes[0].text(0.5, 0.5, 'ACF plot failed', ha='center', va='center', transform=axes[0].transAxes)\n    axes[1].text(0.5, 0.5, 'ACF plot failed', ha='center', va='center', transform=axes[1].transAxes)\n\nplt.tight_layout(); plt.show()\n\n# Ljung-Box test\ntry:\n    lb_result = acorr_ljungbox(ret_clean, lags=10, return_df=True)\n    print('Ljung-Box Test (H0: no autocorrelation):')\n    print(lb_result)\nexcept:\n    print('Ljung-Box test not available')")

# Cell 36
nb.add_markdown("**Autocorrelation Interpretation:**\n- Returns show minimal autocorrelation → market is relatively efficient\n- **Squared returns** show strong autocorrelation → volatility clusters (GARCH effect)\n- This justifies using GARCH-family models for volatility forecasting")

# Cell 37
nb.add_code("# ============================================================\n# 6.2 Value at Risk (VaR)\n# ============================================================\nconfidence_levels = [0.95, 0.99]\nprint('VALUE AT RISK (VaR)')\nprint('=' * 50)\n\nfor cl in confidence_levels:\n    # Historical VaR\n    h_var = ret_clean.quantile(1-cl) * 100\n    \n    # Parametric VaR (assuming normal)\n    p_var = (ret_clean.mean() + stats.norm.ppf(1-cl) * ret_clean.std()) * 100\n    \n    print(f'\\n{cl*100:.0f}% Confidence Level:')\n    print(f'  Historical VaR: {h_var:.3f}% (worst day in {1/(1-cl):.0f})')\n    print(f'  Parametric VaR: {p_var:.3f}%')\n    print(f'  Gap:            {abs(h_var - p_var):.3f}% (fat tails effect)')")

# Cell 38
nb.add_code("# ============================================================\n# 6.3 Monthly seasonality\n# ============================================================\ndf['Month'] = df.index.month\nmonthly = df.groupby('Month')['Log_Return'].agg(['mean', 'std', 'count'])\nmonthly['mean_pct'] = monthly['mean'] * 100\n\nfig, ax = plt.subplots(figsize=(14, 6))\ncolors_m = ['#2ECC71' if x > 0 else '#E74C3C' for x in monthly['mean_pct']]\nax.bar(monthly.index, monthly['mean_pct'], color=colors_m, alpha=0.7, edgecolor='white')\nax.set_xlabel('Month')\nax.set_ylabel('Average Daily Return (%)')\nax.set_title('Monthly Seasonality — Average Daily Return', fontweight='bold')\nax.set_xticks(range(1, 13))\nax.set_xticklabels(['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])\nax.axhline(0, color='black', linewidth=0.5)\nplt.tight_layout(); plt.show()\n\nprint('Monthly Return Seasonality:')\nfor m, row in monthly.iterrows():\n    month_name = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'][m-1]\n    print(f'  {month_name}: {row[\"mean_pct\"]:+.4f}% avg daily return ({row[\"count\"]:.0f} obs)')")

# Cell 39
nb.add_markdown("**Seasonality Finding:** October tends to have mixed returns historically (not just 2024). This is consistent with the global \"October Effect\" — a psychological bias where investors expect market weakness in October due to historical crashes (1929, 1987, 2008, 2024).")

# Cell 40
nb.add_code("# ============================================================\n# 6.4 Day-of-week effect\n# ============================================================\ndf['DayOfWeek'] = df.index.dayofweek\ndow = df.groupby('DayOfWeek')['Log_Return'].agg(['mean', 'std'])\ndow['mean_pct'] = dow['mean'] * 100\n\nfig, ax = plt.subplots(figsize=(10, 5))\ncolors_d = ['#2ECC71' if x > 0 else '#E74C3C' for x in dow['mean_pct']]\nax.bar(dow.index, dow['mean_pct'], color=colors_d, alpha=0.7)\nax.set_xticks(range(5))\nax.set_xticklabels(['Monday','Tuesday','Wednesday','Thursday','Friday'])\nax.set_ylabel('Average Daily Return (%)')\nax.set_title('Day-of-Week Effect', fontweight='bold')\nax.axhline(0, color='black', linewidth=0.5)\nplt.tight_layout(); plt.show()")

# Cell 41
nb.add_markdown("---\n\n## Part 7: Summary & Key Takeaways\n\n### 🔑 Key Findings from EDA:\n\n1. **Non-Normal Returns:** Returns are leptokurtic (fat tails) with negative skew — traditional risk models underestimate tail risk\n2. **Regime Matters:** The recovery phase (2020-2021) generated extraordinary returns with reasonable volatility\n3. **Volume Confirms:** Volume spikes validate price moves — the Oct 2024 decline was accompanied by genuine selling pressure\n4. **Sector Correlation:** Tata Motors correlates with the auto sector but has higher idiosyncratic risk\n5. **Oct 2024 ≠ COVID:** The Oct 2024 event was shorter, less severe, and driven by sentiment rather than fundamentals\n6. **Seasonality:** Weak October effect exists, but is not statistically significant on its own\n\n### Next Steps:\nThese EDA findings guide our modeling approach:\n- Use regime-aware features (NB08-10)\n- Account for fat tails in risk management (NB12)\n- Incorporate volume as a signal (NB09)\n\n---\n*Next: Notebook 06 — Sentiment Deep Dive*")

nb.save("notebooks/05_EDA_Trends_Regimes.ipynb")
