from notebook_generator import NotebookBuilder
nb = NotebookBuilder()

nb.add_markdown("# 💰 Notebook 12: Trading Strategy Backtesting\n\n---\n\n**Author:** Dnyanesh  \n**Date:** February 2025  \n**Series:** Tata Motors Deep Dive (12 of 13)\n\n## Objective\n\nA model that predicts direction is useless if it can't make money. We:\n1. Build a **walk-forward backtest** using ML predictions\n2. Compare against **Buy & Hold** benchmark\n3. Calculate **risk-adjusted metrics** (Sharpe, Sortino, Max Drawdown)\n4. Analyze performance across **market regimes**\n\n### The Core Question:\n> **Can our ML model beat simply buying Tata Motors and holding?**")

nb.add_code("import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.ensemble import RandomForestClassifier\nimport os, warnings\nwarnings.filterwarnings('ignore')\nsns.set_style('whitegrid')\nPROCESSED_DIR = '../data/processed'\nprint('✅ Environment ready')")

nb.add_code("# Load data\ndf = pd.read_csv(os.path.join(PROCESSED_DIR, 'tata_motors_all_features.csv'), index_col=0, parse_dates=True) if os.path.exists(os.path.join(PROCESSED_DIR, 'tata_motors_all_features.csv')) else pd.read_csv(os.path.join(PROCESSED_DIR, 'tata_motors_clean.csv'), index_col=0, parse_dates=True)\nif 'Log_Return' not in df.columns:\n    df['Log_Return'] = np.log(df['Close'] / df['Close'].shift(1))\ndf['Target'] = (df['Log_Return'].shift(-1) > 0).astype(int)\n\nsel_file = os.path.join(PROCESSED_DIR, 'selected_features.csv')\nif os.path.exists(sel_file):\n    selected = [f for f in pd.read_csv(sel_file).iloc[:, 0].tolist() if f in df.columns]\nelse:\n    exclude = ['Target', 'Regime', 'Cluster', 'Log_Return', 'Simple_Return', 'Price_Change']\n    selected = [c for c in df.select_dtypes(include=[np.number]).columns if c not in exclude][:15]\n\nmodel_df = df[selected + ['Target', 'Close', 'Log_Return']].dropna()\nprint(f'Data: {model_df.shape}, Features: {len(selected)}')")

nb.add_markdown("---\n\n## Part 1: Strategy Design\n\n### Signal Rules:\n- **BUY** (position = 1): Model predicts UP with probability > 0.5\n- **SELL** (position = 0): Model predicts DOWN\n- **Long-only**: No short selling\n\n### Realistic Assumptions:\n| Parameter | Value | Rationale |\n|-----------|-------|-----------|\n| Transaction cost | 0.1% | Brokerage + STT + GST |\n| Starting capital | ₹100,000 | Standard amount |\n| Position sizing | 100% | Fully invested or fully cash |")

nb.add_code("TRANSACTION_COST = 0.001\nSTARTING_CAPITAL = 100000\nRETRAIN_PERIOD = 63\nMIN_TRAIN = 252\n\nprint(f'Transaction cost: {TRANSACTION_COST*100}%')\nprint(f'Starting capital: ₹{STARTING_CAPITAL:,.0f}')\nprint(f'Retrain period: {RETRAIN_PERIOD} days')")

nb.add_markdown("### Walk-Forward Backtesting:\n```\nPeriod 1: [===Train===][Trade Q1]\nPeriod 2: [=====Train=====][Trade Q2]\nPeriod 3: [=======Train=======][Trade Q3]\n```\nThis simulates real-world conditions where you periodically refit your model.")

nb.add_code("scaler = StandardScaler()\nresults = []\ncurrent_position = 0\n\n# Auto-adjust MIN_TRAIN for shorter datasets\nactual_min_train = min(MIN_TRAIN, max(int(len(model_df) * 0.6), 30))\nif len(model_df) < 50:\n    print(f'⚠️  Very short dataset ({len(model_df)} rows). Backtest will be limited.')\n\nfor i in range(actual_min_train, len(model_df), RETRAIN_PERIOD):\n    train_end = i\n    test_end = min(i + RETRAIN_PERIOD, len(model_df))\n    train_data = model_df.iloc[:train_end]\n    test_data = model_df.iloc[train_end:test_end]\n    if len(test_data) == 0: break\n    \n    X_train_scaled = scaler.fit_transform(train_data[selected])\n    X_test_scaled = scaler.transform(test_data[selected])\n    \n    model = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42, n_jobs=-1)\n    model.fit(X_train_scaled, train_data['Target'])\n    probs = model.predict_proba(X_test_scaled)[:, 1]\n    signals = (probs > 0.5).astype(int)\n    \n    for j, (idx, row) in enumerate(test_data.iterrows()):\n        signal = signals[j]\n        cost = TRANSACTION_COST if signal != current_position else 0\n        strategy_return = (row['Log_Return'] - cost) if current_position == 1 else -cost\n        results.append({'Date': idx, 'Close': row['Close'], 'Signal': signal,\n                       'Position': current_position, 'Market_Return': row['Log_Return'],\n                       'Strategy_Return': strategy_return, 'Probability': probs[j]})\n        current_position = signal\n\nif len(results) == 0:\n    print('⚠️  No backtest results — dataset too small for walk-forward.')\n    print('     Creating placeholder with buy-and-hold returns.')\n    bt = model_df[['Close', 'Log_Return']].copy()\n    bt['Signal'] = 1\n    bt['Position'] = 1\n    bt['Market_Return'] = bt['Log_Return']\n    bt['Strategy_Return'] = bt['Log_Return']\n    bt['Probability'] = 0.5\nelse:\n    bt = pd.DataFrame(results).set_index('Date')\nprint(f'Backtest: {bt.index.min().date()} to {bt.index.max().date()}')\nprint(f'Days: {len(bt)}, Invested: {(bt[\"Position\"]==1).mean()*100:.1f}%')")

nb.add_markdown("---\n\n## Part 2: Performance Analysis")

nb.add_code("bt['Cum_Market'] = (1 + bt['Market_Return']).cumprod()\nbt['Cum_Strategy'] = (1 + bt['Strategy_Return']).cumprod()\nbt['Market_Value'] = bt['Cum_Market'] * STARTING_CAPITAL\nbt['Strategy_Value'] = bt['Cum_Strategy'] * STARTING_CAPITAL\n\nprint(f'Buy & Hold:  ₹{bt[\"Market_Value\"].iloc[-1]:,.0f}')\nprint(f'ML Strategy: ₹{bt[\"Strategy_Value\"].iloc[-1]:,.0f}')")

nb.add_code("def calc_metrics(returns, name):\n    total_ret = (1 + returns).prod() - 1\n    ann_ret = returns.mean() * 252\n    ann_vol = returns.std() * np.sqrt(252)\n    sharpe = (returns.mean() / returns.std() * np.sqrt(252)) if returns.std() > 0 else 0\n    down = returns[returns < 0]\n    sortino = (returns.mean() / down.std() * np.sqrt(252)) if len(down) > 0 and down.std() > 0 else 0\n    cum = (1 + returns).cumprod()\n    max_dd = ((cum - cum.expanding().max()) / cum.expanding().max()).min()\n    win = (returns > 0).mean()\n    return {'Strategy': name, 'Total Return': f'{total_ret*100:+.1f}%', 'Ann. Return': f'{ann_ret*100:+.1f}%',\n            'Ann. Vol': f'{ann_vol*100:.1f}%', 'Sharpe': f'{sharpe:.2f}', 'Sortino': f'{sortino:.2f}',\n            'Max DD': f'{max_dd*100:.1f}%', 'Win Rate': f'{win*100:.1f}%'}\n\nmetrics = pd.DataFrame([calc_metrics(bt['Market_Return'], 'Buy & Hold'),\n                       calc_metrics(bt['Strategy_Return'], 'ML Strategy')]).set_index('Strategy')\nprint('\\nPERFORMANCE COMPARISON')\nprint(metrics)")

nb.add_code("fig, axes = plt.subplots(3, 1, figsize=(18, 14), gridspec_kw={'height_ratios': [3, 1, 1]})\nax = axes[0]\nax.plot(bt.index, bt['Market_Value'], color='gray', linewidth=1.5, label='Buy & Hold', alpha=0.7)\nax.plot(bt.index, bt['Strategy_Value'], color='#2ECC71', linewidth=2, label='ML Strategy')\nax.axhline(STARTING_CAPITAL, color='black', linestyle=':', alpha=0.3)\nax.set_title(f'Equity Curve (Start: ₹{STARTING_CAPITAL:,.0f})', fontsize=14, fontweight='bold')\nax.set_ylabel('Portfolio Value (INR)'); ax.legend(fontsize=12); ax.grid(True, alpha=0.3)\n\nax = axes[1]\nfor label, col, color in [('Buy & Hold', 'Market_Return', 'gray'), ('Strategy', 'Strategy_Return', '#E74C3C')]:\n    cum = (1 + bt[col]).cumprod(); peak = cum.expanding().max()\n    dd = (cum - peak) / peak * 100\n    ax.fill_between(bt.index, dd, 0, color=color, alpha=0.3, label=label)\nax.set_title('Drawdown', fontweight='bold'); ax.set_ylabel('DD (%)'); ax.legend(fontsize=10)\n\nax = axes[2]\nax.fill_between(bt.index, bt['Position'], 0, step='pre', alpha=0.3, color='#3498DB')\nax.set_title('Position (1=Invested, 0=Cash)', fontweight='bold'); ax.set_ylim(-0.1, 1.1)\nplt.tight_layout(); plt.show()")

nb.add_markdown("**Equity Curve Interpretation:**\n- The ML strategy should have lower drawdowns (goes to cash during predicted downturns)\n- Buy & Hold captures all upside AND downside\n- The position chart shows how often the model is invested")

nb.add_markdown("---\n\n## Part 3: Trade Analysis")

nb.add_code("trades = bt['Signal'].diff().ne(0).sum()\nprint('TRADE STATISTICS')\nprint(f'Signal changes: {trades}')\nprint(f'Avg trades/month: {trades/(len(bt)/21):.1f}')")

nb.add_code("invested = bt[bt['Position'] == 1]\ncash = bt[bt['Position'] == 0]\nprint('\\nWhen INVESTED:')\nif len(invested) > 0:\n    print(f'  Avg return: {invested[\"Market_Return\"].mean()*100:+.4f}%/day')\n    print(f'  Win rate: {(invested[\"Market_Return\"] > 0).mean()*100:.1f}%')\nprint('\\nWhen in CASH:')\nif len(cash) > 0:\n    print(f'  Market avg: {cash[\"Market_Return\"].mean()*100:+.4f}%/day')\n    avoided = cash[cash['Market_Return'] < 0]['Market_Return'].sum()\n    missed = cash[cash['Market_Return'] > 0]['Market_Return'].sum()\n    print(f'  Loss avoided: {avoided*100:+.2f}%')\n    print(f'  Gain missed: {missed*100:+.2f}%')")

nb.add_code("# Monthly returns heatmap\nbt['Year'] = bt.index.year; bt['Month'] = bt.index.month\nmonthly = bt.groupby(['Year', 'Month'])['Strategy_Return'].apply(lambda x: (1+x).prod()-1).unstack()\nfig, ax = plt.subplots(figsize=(14, max(4, len(monthly)*0.6)))\nsns.heatmap(monthly*100, annot=True, fmt='.1f', cmap='RdYlGn', center=0, ax=ax, linewidths=0.5,\n           xticklabels=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])\nax.set_title('Monthly Strategy Returns (%)', fontweight='bold', fontsize=13)\nplt.tight_layout(); plt.show()")

nb.add_markdown("---\n\n## Part 4: Regime Performance")

nb.add_code("def assign_regime(date):\n    if date < pd.Timestamp('2020-03-01'): return 'Pre-COVID'\n    elif date < pd.Timestamp('2020-05-01'): return 'COVID Crash'\n    elif date < pd.Timestamp('2022-01-01'): return 'Recovery'\n    elif date < pd.Timestamp('2024-10-01'): return 'Post-COVID'\n    else: return 'Oct 2024'\n\nbt['Regime'] = bt.index.map(assign_regime)\nregime_perf = []\nfor regime in ['Pre-COVID', 'COVID Crash', 'Recovery', 'Post-COVID', 'Oct 2024']:\n    mask = bt['Regime'] == regime\n    if mask.sum() > 5:\n        s = bt.loc[mask, 'Strategy_Return']; m = bt.loc[mask, 'Market_Return']\n        regime_perf.append({'Regime': regime, 'Days': mask.sum(),\n                          'Market%': f'{m.mean()*252*100:+.1f}', 'Strategy%': f'{s.mean()*252*100:+.1f}',\n                          'Invested': f'{bt.loc[mask,\"Position\"].mean()*100:.0f}%'})\nprint('REGIME PERFORMANCE')\nprint(pd.DataFrame(regime_perf).to_string(index=False))")

nb.add_code("rp = pd.DataFrame(regime_perf).set_index('Regime')\nrp['Market%'] = rp['Market%'].astype(float); rp['Strategy%'] = rp['Strategy%'].astype(float)\nfig, ax = plt.subplots(figsize=(14, 6))\nx = np.arange(len(rp)); width = 0.35\nax.bar(x - width/2, rp['Market%'], width, label='Buy & Hold', color='gray', alpha=0.7)\nax.bar(x + width/2, rp['Strategy%'], width, label='ML Strategy', color='#2ECC71', alpha=0.8)\nax.set_xticks(x); ax.set_xticklabels(rp.index, rotation=15)\nax.set_ylabel('Ann. Return (%)'); ax.set_title('Strategy vs Buy & Hold by Regime', fontweight='bold', fontsize=14)\nax.legend(fontsize=12); ax.axhline(0, color='black', linewidth=0.5)\nplt.tight_layout(); plt.show()")

nb.add_markdown("**Regime Insights:**\n- The strategy adds most value during **crash periods** (going to cash)\n- During strong uptrends, Buy & Hold may outperform\n- The real value is **risk management**")

nb.add_markdown("---\n\n## Part 5: What-If Analysis")

nb.add_code("rets = bt['Market_Return'].sort_values()\nprint('WHAT-IF: AVOIDING THE WORST DAYS')\nfor n in [5, 10, 20, 50]:\n    modified = bt['Market_Return'].copy()\n    modified.loc[rets.head(n).index] = 0\n    total = (1 + modified).prod()\n    bh = (1 + bt['Market_Return']).prod()\n    print(f'Avoid worst {n:2d} days: {(total-1)*100:+.1f}% vs B&H {(bh-1)*100:+.1f}%')\nprint('\\n→ Avoiding the worst 10 days dramatically changes returns.')")

nb.add_code("bt.to_csv(os.path.join(PROCESSED_DIR, 'backtest_results.csv'))\nmetrics.to_csv(os.path.join(PROCESSED_DIR, 'strategy_metrics.csv'))\nprint('✅ Saved: backtest_results.csv, strategy_metrics.csv')")

nb.add_markdown("---\n\n## Summary\n\n### 🔑 Key Findings:\n\n1. **Risk reduction > Return enhancement** — ML strategy's primary value is lower drawdowns\n2. **Transaction costs matter** — High-frequency trading erodes edge\n3. **Regime awareness helps** — Best during crash periods\n4. **Worst-days analysis** — Avoiding 10 worst days transforms returns\n5. **Buy & Hold is hard to beat** — Most active strategies underperform after costs\n\n### Practical Implications:\n- Use ML as a **risk indicator**, not pure trading signal\n- Reduce position size when model predicts DOWN\n- Combine with sentiment and technical signals\n- Rebalance quarterly to reduce transaction costs\n\n---\n*Next: Notebook 13 — Final Synthesis*")

nb.save("notebooks/12_Strategy_Backtesting.ipynb")
