import os
from reportlab.lib.pagesizes import letter
from reportlab.platypus import Paragraph, Spacer, Image, Table, TableStyle, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_JUSTIFY, TA_CENTER, TA_LEFT

def create_custom_styles():
    """Create custom paragraph styles for the report."""
    styles = getSampleStyleSheet()
    
    # Chapter Title
    styles.add(ParagraphStyle(
        name='ChapterTitle',
        parent=styles['Heading1'],
        fontSize=24,
        leading=30,
        spaceAfter=20,
        textColor=colors.darkblue,
        alignment=TA_center_if_possible(styles['Heading1'])
    ))
    
    # Section Title
    styles.add(ParagraphStyle(
        name='SectionTitle',
        parent=styles['Heading2'],
        fontSize=18,
        leading=22,
        spaceBefore=15,
        spaceAfter=10,
        textColor=colors.black
    ))
    
    # Body Text
    styles.add(ParagraphStyle(
        name='BodyTextCustom',
        parent=styles['Normal'],
        fontSize=12,
        leading=16,
        alignment=TA_JUSTIFY,
        spaceAfter=10
    ))
    
    # Code Block
    styles.add(ParagraphStyle(
        name='CodeBlock',
        parent=styles['Code'],
        fontSize=10,
        leading=12,
        fontName='Courier',
        backColor=colors.lightgrey,
        borderPadding=5,
        spaceAfter=10
    ))
    
    # Insight/Highlight Box
    styles.add(ParagraphStyle(
        name='InsightBox',
        parent=styles['Normal'],
        fontSize=12,
        leading=16,
        backColor=colors.whitesmoke,
        borderColor=colors.green,
        borderWidth=1,
        borderPadding=10,
        spaceAfter=15,
        textColor=colors.darkgreen
    ))

    # Caption
    styles.add(ParagraphStyle(
        name='Caption',
        parent=styles['Italic'],
        fontSize=10,
        leading=12,
        alignment=TA_CENTER,
        spaceAfter=10,
        textColor=colors.gray
    ))

    return styles

def TA_center_if_possible(style):
    try:
        return TA_CENTER
    except:
        return style.alignment

def create_header_footer(canvas, doc):
    """Draw header and footer on each page."""
    canvas.saveState()
    
    # Header
    canvas.setFont('Helvetica', 9)
    canvas.drawRightString(letter[0] - 50, letter[1] - 30, "Magnum Opus: Stock Market Alchemist")
    canvas.line(50, letter[1] - 35, letter[0] - 50, letter[1] - 35)
    
    # Footer
    canvas.setFont('Helvetica', 9)
    canvas.drawString(50, 30, "Generated by Antigravity")
    canvas.drawRightString(letter[0] - 50, 30, f"Page {doc.page}")
    canvas.line(50, 40, letter[0] - 50, 40)
    
    canvas.restoreState()

def add_dataframe_table(story, df, title=None):
    """Helper to add a pandas DataFrame as a ReportLab table."""
    if title:
        story.append(Paragraph(f"<b>{title}</b>", create_custom_styles()['BodyTextCustom']))
        story.append(Spacer(1, 5))
        
    data = [df.columns.tolist()] + df.values.tolist()
    
    # Format data (simplify logic for now, can be enhanced)
    formatted_data = []
    for row in data:
        new_row = []
        for item in row:
            if isinstance(item, float):
                new_row.append(f"{item:.2f}")
            else:
                new_row.append(str(item)[:50]) # Truncate long text
        formatted_data.append(new_row)
        
    t = Table(formatted_data)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    story.append(t)
    story.append(Spacer(1, 15))

def add_img(story, path, cap, s=None, w=6.0, h=3.3):
    """
    Add an image to the story with a caption.
    s: styles dictionary (optional, if not provided, uses default)
    """
    if os.path.exists(path):
        if s is None:
            s_obj = create_custom_styles()
            style_caption = s_obj['Caption']
        else:
            style_caption = s['Caption']
            
        try:
            img = Image(path, width=w*inch, height=h*inch)
            story.append(img)
            story.append(Paragraph(f"<b>{cap}</b>", style_caption))
            story.append(Spacer(1, 12))
        except Exception as e:
            print(f"Warning: Could not add image {path} - {e}")
    else:
        print(f"Warning: Image path not found: {path}")
